### ISSUE TITLE
improve heuristics

### ISSUE THREAD

**Issue by sim0023** [konsolas/AAC-Issues#1433] opened 2018-07-27 20:07 UTC
Previous issue got closed, but it's still a valid issue - heuristics needs to be improved - and if you close this issue again, it will just show how much you care about our suggestions; nothing.

--
Too many false positives with high ping, false flags good players, doesn't detect some paid clients. It should get a huge re-work, or replaced with something else. Currently, it's unstable and this has been the case for a year. And don't say that I need to report false positives, because I've seen multiple issues about patterns which have said to be fixed, but still have lots of issues. It's just not worth it reporting anymore, because if it should've been improved by it, people wouldn't complain about false flags. I hope that you can spend more time on this check, than any other check.

**Comment by Janmm14** [comment] 2018-07-28 10:55
#1428

**Comment by Photon-GitHub** [comment] 2018-08-01 17:04
We will close this issue as it is a duplicate of #1428, please comment on that issue.

**Closed by Photon-GitHub** 2018-08-01 17:04 UTC
