### ISSUE TITLE
Players stuck in blocks can't move out

### ISSUE THREAD

**Issue by botany111** [konsolas/AAC-Issues#1845] opened 2019-12-27 14:34 UTC
### Issue description
When the door is opened, if the player is in the door, there will be unlimited SETBACK

Occurs when the player is stuck in a block

Wooden door , sand ...

Video: https://streamable.com/19nu5
### Core information
**Server version**: paper-1.15.1

**AAC version**: AAC-4.3.4

**ProtocolLib version**:  4.5.0-SNAPSHOT-b443

**Plugin list**: 

Special environment information
ViaVersion version: n/a

ProtocolSupport version: n/a

ViaBackwards version: n/a

BungeeCord plugins: n/a

Configuration

**Comment by Zaino60** [comment] 2020-01-04 03:06
Experiencing the same issue at carpets. https://gyazo.com/f042868e8f4982f6489b98f0e3405323

**Comment by konsolas** [comment] 2020-01-08 17:50
Closing as duplicate of #1849

**Closed by konsolas** 2020-01-08 17:50 UTC
Labels: 1. bug, 2. move, 4. duplicate
