### ISSUE TITLE
Bow Speed Bug

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#127] opened 2016-11-02 11:06 UTC
When you pull back a bow, then let go on flat land, it flags for speed. The faster you spam the bow, the more you get flagged. (Doesn't work on Ice.) https://www.youtube.com/watch?v=FAYdqZoN3n4

**Comment by Rqcco** [comment] 2016-11-02 11:08
Also, is autoclicker/triggerbot a flag yet?

**Comment by konsolas** [comment] 2016-11-02 22:45
Going to merge the two issues and close this as a duplicate of #128.

**Closed by konsolas** 2016-11-02 22:45 UTC
Labels: bug
