### ISSUE TITLE
Console Error every Second

### ISSUE THREAD

**Issue by RageKB** [konsolas/AAC-Issues#2296] opened 2021-07-29 17:56 UTC
Error starting plugin, latest version + protocol lib

1.15.2
Localhost

[19:55:39] [Server thread/WARN]: [AAC5] Task #5 for AAC5 v5.2.0 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.lo
	at me.konsolas.aac.eo.a(eo.java:13) ~[?:?]
	at me.konsolas.aac.ca.a(ca.java:218) ~[?:?]
	at me.konsolas.aac.ca.<init>(ca.java:283) ~[?:?]
	at me.konsolas.aac.cz.<init>(cz.java:17) ~[?:?]
	at me.konsolas.aac.iS.a(iS.java:78) ~[?:?]
	at me.konsolas.aac.iS.a(iS.java:82) ~[?:?]
	at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:1) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

**Comment by NoneTirex** [comment] 2021-08-02 08:31
Duplicate of #2294

**Comment by Janmm14** [comment] 2021-08-02 09:04
Duplicate of #2294

**Closed by Janmm14** 2021-08-02 09:04 UTC
Labels: 1. error, 4. duplicate
