### ISSUE TITLE
Soil glitching.

### ISSUE THREAD

**Issue by wasder** [konsolas/AAC-Issues#359] opened 2017-01-08 14:55 UTC
SOIL is exluded from phase check. And there is nothing in AAC logs, that is strange.
https://dl.dropboxusercontent.com/u/19928258/ShareX/2017/01/2017-01-08_17-42-25.mp4

**Comment by Rqcco** [comment] 2017-01-08 15:04
Duplicate of #291

**Closed** 2017-01-08 15:04 UTC
Labels: duplicate
