### ISSUE TITLE
Advanced AntiCheat does not work with JDK 9

### ISSUE THREAD

**Issue by TreyRuffy** [konsolas/AAC-Issues#1084] opened 2017-11-20 18:57 UTC
### Issue description
https://hastebin.com/wazexeqebo.vbs

The anti-cheat does not work with JDK 9. Each time it is loaded, it will give this same error.

### Core information
**Server version**: 1.12 (Also tried on 1.8.8)

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: ProtocolLib, AAC, CommandBlocker

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Nothing has been edited.

**Comment by konsolas** [comment] 2017-11-20 21:27
duplicate of #1021

**Closed by konsolas** 2017-11-20 21:27 UTC
Labels: 4. duplicate
