### ISSUE TITLE
click commands

### ISSUE THREAD

**Issue by MrDiggerFTW** [konsolas/AAC-Issues#197] opened 2016-11-15 00:22 UTC
Can you plz add click commands like on G.W.E.N you can tp an HCGAMES? like more like HCGAMES tho
https://gyazo.com/4f934b90195adf82039d320dff729574

**Comment by Rqcco** [comment] 2016-11-15 00:59
Just realized this is a duplicate of #153

**Closed** 2016-11-15 00:59 UTC
Labels: duplicate, feature
