### ISSUE TITLE
Walking on farmland on 1.12.X - instant fly flag

### ISSUE THREAD

**Issue by Tyloonie** [konsolas/AAC-Issues#1109] opened 2017-12-09 17:11 UTC
### Issue description
When walking on farmland (hoed dirt) on Minecraft 1.12.X (client side version), you instantly get flagged for flyhack. This issue has been there for a while now, surprised no one else has noticed this.
Showcase: https://gyazo.com/ee2800e17755b4e15fedce06e67bb1e7

### Core information
**Server version**: Spigot-1.8.8

**AAC version**: 3.3.6 (newest)

**ProtocolLib version**: 4.3.0 (newest)

**Plugin list**: Keeping it private as I believe other plugins have nothing to do with this particular issue.

### Special environment information
**ViaVersion version**: 1.3.0 (newest)

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: BungeePerms, SlashServer, ServerListPlus

**Comment by Janmm14** [comment] 2017-12-09 17:43
Duplicate of #922

**Closed by Janmm14** 2017-12-09 17:43 UTC
