### ISSUE TITLE
AAC cancels teleport event

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#850] opened 2017-07-29 09:10 UTC
### Issue description
https://youtu.be/jKyw91qeOiM
https://youtu.be/PL76zSdF2D8
This is a custom minigame of mine.
In the second video, after a round ends, players are supposed to teleport back to the spawn, but a player (Gun_Master) wasn't teleported back to the spawn.
(Players who are not on the boat will die and change game mode to spectator, and then change back to 
adventure when they're teleported back to the spawn)

### Core information
**Server version**: PaperSpigot 1.11.2

**AAC version**: 3.2.2 b1

**ProtocolLib version**: 4.3.0

**Plugin list**: upon request

### Special environment information
**ProtocolSupport version**: 4.26.dev

**BungeeCord plugins**: upon request

### Configuration
Default configuration.

**Comment by Photon-GitHub** [comment] 2017-07-29 13:40
Please provide the AAC log of the round or record with verbose enabled as we cannot even confirm that this bug originated from AAC.

**Comment by MClausz** [comment] 2017-07-29 15:21
This is the log at the time this issue happened.
https://pastebin.com/1u9td3pe
I've made a custom plugin that cancels all AAC checks to FPMC checked players, and this issue never happen to checked players.

**Comment by CeIebrimbor** [comment] 2017-08-25 17:56
Note: This occurs without ProtocolSupport environment

**Comment by MClausz** [comment] 2017-08-26 03:47
Will it help to the decrease this if I cancel violation event when a plauyer are just teleported?

**Comment by MClausz** [comment] 2017-08-26 11:11
Detailed video: https://youtu.be/jKyw91qeOiM
This becamse a serious issue now, and haven't fixed for MONTHs.

**Comment by MClausz** [comment] 2017-09-03 07:58
@konsolas please take a look at this

**Comment by AfkF24** [comment] 2017-09-03 22:42
Same issue. Moving right after a teleportation (or during a teleportation) will teleport/setback you back to your previous location. It's getting a bit annoying & frustrating to deal with now, specially on a minigames server.

**Comment by MClausz** [comment] 2017-09-30 07:23
@konsolas

**Comment by Janmm14** [comment] 2017-10-12 22:05
Likely a duplicate of #1001.
In cade its not fixed with AAC 3.3.4, please request a reopen.

**Comment by MClausz** [comment] 2017-10-14 05:13
It's is still not fixed with 3.3.4, please reopen @Janmm14

**Comment by Janmm14** [comment] 2017-10-14 07:46
Please attach a debug log when this happens with AAC 3.3.4-b1.

**Comment by MClausz** [comment] 2017-10-14 09:12
A player in my server reported that this issue still occur. This is the log at the time his teleportation being canceled. TPS drops due to mass teleport.
`[14-10-2017 09:23:10.275] ThaiKhang908 failed BadPackets: sent 20 moves in 3 ticks. [ping:182 tps:14.23] VL:5
`
And then ThaiKhang908 wasn't teleported.

**Closed** 2017-12-10 12:57 UTC
Labels: 1. bug, 2. move, 3. insufficient info, 4. inactivity

**Comment by MClausz** [comment] 2018-03-07 05:42
@konsolas @Janmm14 this bug is back, please reopen this issue
