### ISSUE TITLE
Block-Speed bypass

### ISSUE THREAD

**Issue by MrHeiLo** [konsolas/AAC-Issues#1147] opened 2018-01-12 12:57 UTC
### Issue description
https://www.youtube.com/watch?v=vWGtMtuOFVE (Block-Speed?) ~by haze.
Just watch the Pre-Intro

### Core information
**Server version**: 1.8.?

**AAC version**: 3.3.7

**ProtocolLib version**: Unknown

**Plugin list**: Unknown

### Special environment information
**ViaVersion version**: Unknown

**ProtocolSupport version**: Unknown

**ViaBackwards version**: Unknown

**BungeeCord plugins**: Unknown

**Comment by konsolas** [comment] 2018-01-12 21:37
duplicate of #1142

**Closed by konsolas** 2018-01-12 21:37 UTC
Labels: 1. bypass, 2. move, 4. duplicate
