### ISSUE TITLE
NoFall bypass

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1776] opened 2019-09-15 18:39 UTC
### Issue description

NoFall bypass on Wurst

Wurst cheatclient (1.12.2)
Video: https://radikal.ru/video/rB34IvcuxHn
(Console verbose is enabled)

### Core information
**Server version**:  CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib, AAC

### Special environment information
**ViaVersion version**: No

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: No

### Configuration

Default

**Comment by konsolas** [comment] 2019-12-03 19:01
duplicate of #1737

**Closed by konsolas** 2019-12-03 19:01 UTC
Labels: 1. bypass, 2. move, 4. duplicate
