### ISSUE TITLE
false positive slabs

### ISSUE THREAD

**Issue by Henriks9** [konsolas/AAC-Issues#1250] opened 2018-03-02 15:19 UTC
Test Server

Video:

https://www.youtube.com/watch?v=w6RqbK7DGBs&feature=youtu.be

**Comment by Minemaniak** [comment] 2018-03-02 15:58
I think it's duplicate of https://github.com/konsolas/AAC-Issues/issues/1221

**Comment by Photon-GitHub** [comment] 2018-03-02 23:48
Duplicate of #1221

**Closed by Photon-GitHub** 2018-03-02 23:48 UTC
Labels: 1. bug
