### ISSUE TITLE
Trampled Crop SneakJump = Fly (1.11.2)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#383] opened 2017-01-21 20:42 UTC
https://youtu.be/sIpbScopAbw

Recently trampled crops while sneaking and jumping = Fly VL14

1.11.2

**Comment by Janmm14** [comment] 2017-01-22 00:13
So its 1.11.2-only?

**Comment by CeIebrimbor** [comment] 2017-01-22 00:25
No clue. Only tested 1.11 today since 1.11 is always an afterthought with development. Still seems to be the case.

**Comment by CeIebrimbor** [comment] 2017-01-22 16:39
Not fixed in 3.0.2-b1

**Comment by Photon-GitHub** [comment] 2017-04-02 17:15
I cannot reproduce this anymore, therefore I will close this as fixed.

**Closed by Photon-GitHub** 2017-04-02 17:15 UTC
Labels: bug, move, unimportant
