### ISSUE TITLE
AAC fails to load and blocks logins if Java Profiler is attached using -agentpath startup arguments

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#537] opened 2017-04-03 14:26 UTC
Error when starting up with YourKit. Same error happens without AACAdditionPro as well. 

```java
[10:10:45 INFO]: [AACAdditionPro] Enabling AACAdditionPro v1.6
[10:10:45 WARN]: Exception in thread "Thread-34"
[10:10:45 WARN]: java.lang.ExceptionInInitializerError
[10:10:45 WARN]:        at me.konsolas.iaac.g.run(g.java:45)
[10:10:45 WARN]: Caused by: java.lang.NumberFormatException: For input string: "뻖⫉⁏媟ḭ捾砪ᓤ뤯"
[10:10:45 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[10:10:45 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[10:10:45 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[10:10:45 WARN]:        at me.konsolas.iaac.rt.<clinit>(Unknown Source)
[10:10:45 WARN]:        ... 1 more
```

Then when players try to log in:
```java
[10:10:57 INFO]: UUID of player JRL05 is 3a6010fc-1ceb-4c56-ab38-effcb28c98dd
[10:10:57 INFO]: Disconnecting com.mojang.authlib.GameProfile@6d4c0ce2[id=3a6010fc-1ceb-4c56-ab38-effcb28c98dd,name=JRL05,properties={textures=[com.mojang.authlib.properties.Property@125746fc]},legacy=false] (/127.0.0.1:51353): Server still starting up
```

The issue only happens in 3.1.x. It does not happen in 3.0.x

It's happening in 2 of my 20 servers, the other 18 work fine.

**Comment by MedicOP** [comment] 2017-04-03 17:35
I've also tried re-downloading both 3.1.2 and 3.1.1 multiple times to no avail, it's not caused by file corruption or an invalid config, as I'm using the exact same file and config on 20 servers.

**Comment by Janmm14** [comment] 2017-04-04 00:35
I can't reproduce.
Can you maybe send your version of java?

I do hate these types of errors; although I'm not a creator of aac, I did some research on this issue and a possible problem might be your java version in theory.

**Comment by MedicOP** [comment] 2017-04-04 00:57
It's working fine on 5 other servers running on the same machine. Java version is 1.8.0_45

**Comment by Janmm14** [comment] 2017-04-04 01:04
Hmm, maybe consider updating to latest java 8, maybe its caused by some already-fixed race-condition.
I tried reproducing this error on my pc by restarting a server multiple times, but I was unable to get that error or a similar error. I am using some java 8 version with a three-digit build number. (Am on my phone atm)

**Comment by MedicOP** [comment] 2017-04-04 02:12
It says it's caused by

```java
java.lang.NumberFormatException: For input string: "뻖⫉⁏媟ḭ捾砪ᓤ뤯"
```

I don't see how that can be caused by a JVM bug? Or is it something with the obfuscation AAC uses

**Comment by Janmm14** [comment] 2017-04-04 11:02
Yeah its about the obfuscation stuff.

Thats why I am thinking that this is an edge case and it could in theory be maybe caused by the jvm.

**Comment by konsolas** [comment] 2017-04-04 19:56
@MedicOP can you compute the checksums of AAC.jar in a server with this problem and a server without?

**Comment by MedicOP** [comment] 2017-04-04 20:10
I'm not sure what you mean. It's the exact same AAC.jar in 6 different servers all on the same machine. It works fine on 5 of those servers, it does not work in 1 of them.

I've also tried redownloading AAC.jar from the Spigot resource page multiple times, but it still doesn't work in this specific server. Interestingly the AAC.jar has a different size every time I download it from Spigot, but I assume this has to do with Spigot's anti-piracy system?

**Comment by konsolas** [comment] 2017-04-04 20:14
I'm trying to find out if there is some sort of copying error between the servers.

**Comment by MedicOP** [comment] 2017-04-04 20:19
I made a copy of the server that the problem is happening in as I don't want to have downtime on it. I started up the copied server and the error was still present.

Checksum shows JAR files in this testing server and my Lobby server (which does work correctly) match:

```java
[root@ns500072 servers]# md5sum HCTesting/plugins/AAC.jar
37dee1ef5d6b38c9229b2141468b6ebc  HCTesting/plugins/AAC.jar
[root@ns500072 servers]# md5sum Lobby/plugins/AAC.jar
37dee1ef5d6b38c9229b2141468b6ebc  Lobby/plugins/AAC.jar
```

**Comment by MedicOP** [comment] 2017-04-04 20:20
I'm also on Discord right now if you want to IM

**Comment by MedicOP** [comment] 2017-04-04 21:19
Also I found the guy who reported the same error in Discord last week:
https://discordapp.com/channels/248161240038375435/262588738939387904?jump=297109468422995969

**Comment by Janmm14** [comment] 2017-04-04 23:10
> Interestingly, the AAC.jar has a slightly different size every time I download it from Spigot, but I assume this has to do with Spigot's anti-piracy system?
Correct.

**Comment by MedicOP** [comment] 2017-04-08 18:02
Still present in 3.1.3

```java

[14:02:23 INFO]: [AAC] Enabling AAC v3.1.3
[14:02:23 WARN]: Exception in thread "Thread-34"
[14:02:23 WARN]: java.lang.BootstrapMethodError: call site initialization exception
[14:02:23 WARN]:        at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
[14:02:23 WARN]:        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
[14:02:23 WARN]:        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
[14:02:23 WARN]:        at me.konsolas.iaac.l.run(l.java:28)
[14:02:23 WARN]: Caused by: java.lang.ExceptionInInitializerError
[14:02:23 WARN]:        at me.konsolas.iaac.l.uf(l.java)
[14:02:23 WARN]:        at java.lang.invoke.CallSite.makeSite(CallSite.java:283)
[14:02:23 WARN]:        ... 3 more
[14:02:23 WARN]: Caused by: java.lang.NumberFormatException: For input string: "拉?᭮ᗼ긵弴좜䄿缆댑"
[14:02:23 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[14:02:23 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[14:02:23 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[14:02:23 WARN]:        at me.konsolas.iaac.ml.<clinit>(Unknown Source)
[14:02:23 WARN]:        ... 5 more
```

**Comment by c001man** [comment] 2017-04-09 03:34
Because of a bug of your stringer jar level anti-tamper.
getDeclaredMethods() JVM does not guarantee the same sorted will be returned on different machines or different java version.

Check:
http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/share/vm/classfile/classFileParser.cpp
https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html
"The elements in the array returned are not sorted and are not in any particular order"

**Comment by MedicOP** [comment] 2017-04-09 23:06
I have found the cause of the issue.

It seems every server that I have YourKit Java Profiler manually attached to on startup has the problem:
https://www.yourkit.com/docs/java/help/agent.jsp

YourKit profiler has never given me any issues before, so it didn't even come up in my mind when I was trying to figure this out. The bug definitely still needs to be fixed though, as I imagine more people would want to be able to do Java profiling.

The bug is not present in AAC 3.0.x, it only started happening in 3.1.x.

**Comment by MedicOP** [comment] 2017-04-11 09:41
So we can't use any profilers without removing AAC first? Doesn't make sense to me

**Comment by Janmm14** [comment] 2017-04-11 11:39
although profilers are harmless, they seem to use similar techniques to debuggers or other tools people might try to use for cracking aac.

**Comment by byCaptain** [comment] 2017-06-16 06:17
when it will be fixed, error is not fixed yet

**Comment by UltraX3** [comment] 2017-07-12 23:47
Also experiencing this issue.

**Comment by Janmm14** [comment] 2017-07-13 09:37
To be clear: This is expected behaviour.

**Closed by Janmm14** 2017-07-13 09:37 UTC
Labels: compatibility, error

**Comment by MedicOP** [comment] 2017-07-13 12:17
How can breaking any server that uses something as common as a Java profiler be intended behavior? That's ridiculous

**Comment by Janmm14** [comment] 2017-07-13 13:43
This is not just against java profilers, but against all types of agents to prevent deobfuscation and analysis.

**Comment by MedicOP** [comment] 2017-07-13 13:45
Can't you get in contact with Stringer and ask them how to work around this then?

**Comment by Janmm14** [comment] 2017-07-13 13:50
Uhm there is an option in stringer against agents. And konsolas intentionally enables it.

**Comment by MedicOP** [comment] 2017-07-13 13:51
Then he should disable it..

**Comment by Janmm14** [comment] 2017-07-13 15:55
@MedicOP He probably has a reason to enable that. So he did.

**Comment by marint94** [comment] 2017-09-29 17:15
Ridiculous. I use the a JVM agent (YourKit) all the time to check the performance and this never happened before the 3.1.x update.

**Comment by Janmm14** [comment] 2017-09-29 21:44
Agents provide the possibility of easier deobfuscation and method tracing. That's why the disallow agents check option is enabled.
There is no option and no good way of detecting which agent is there.
