### ISSUE TITLE
Move false positives (1.12.2 client on 1.8.8 server + ViaVersion)

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1836] opened 2019-12-21 08:50 UTC
### Issue description
AAC's Move check kicks players with 1.12.2 client (without mods) on Spigot 1.8.8 server with ViaVersion.
I don't observe the problem with the 1.8.9 client on this server.
Log: https://pastebin.com/VGUsv1cy
### Core information
**Server version**: Spigot 1.8.8

**AAC version**: AAC 4.3.2-b1

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: ViaVersion 2.2.2

**ProtocolSupport version**: no

**ViaBackwards version**: no

**BungeeCord plugins**: no

### Configuration
Celebrimbor's config without any changes.

**Comment by konsolas** [comment] 2019-12-21 10:26
Is any particular geometry/terrain required for this to happen, or does it happen everywhere?

What are the players doing? Does it require them to jump or just move around?

**Comment by konsolas** [comment] 2019-12-21 12:03
Just tried logging in with a 1.12 client on a 1.8.8 server with ViaVersion 2.2.2 and I can't reproduce any false positives. Going to need more information here.

**Comment by konsolas** [comment] 2019-12-26 21:13
@BestMark isn't really sure how this issue was caused or how to reproduce it, and it might have been fixed in a past update.

**Closed by konsolas** 2019-12-26 21:13 UTC
Labels: 2. move, 3. insufficient info, 3. multiversion, ¯\_(ツ)_/¯
