### ISSUE TITLE
v.1.9.10 Highjump Teleport

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#89] opened 2016-10-30 00:03 UTC
I don't know whether this also fixed with the new setback system of fly, however highjump is most likely the check that allowed instant teleportation. (Sending 1 movement packet at target and 1 packet x+1 and y+5)

**Comment by konsolas** [comment] 2016-10-30 09:47
Seems to be a duplicate of #2.

**Closed by konsolas** 2016-10-30 09:47 UTC
Labels: duplicate

**Comment by Janmm14** [comment] 2016-10-30 11:20
Oh, sorry I thought I did not reported that already.
