### ISSUE TITLE
AAC+CC Offline Player Error

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#292] opened 2016-12-27 19:08 UTC
I think AAC needs the same treatment Conditional Commands got with handling of commands when a player is offline (due to previous kick).

https://hastebin.com/ajakewuwok.vbs

Harmless, but silly/spammy.

**Comment by konsolas** [comment] 2016-12-28 11:58
I believe this is a duplicate of #267

**Closed by konsolas** 2016-12-28 11:58 UTC
Labels: duplicate, error
