### ISSUE TITLE
AAC wont load correctly

### ISSUE THREAD

**Issue by ElijahHender** [konsolas/AAC-Issues#1925] opened 2020-03-12 07:55 UTC
Unhandled exception

Type=Segmentation error vmState=0x00040000

J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001

Handler1=00007F74C997CBF0 Handler2=00007F74C92794A0 InaccessibleAddress=0000000000000000

RDI=00000000033CD000 RSI=00000000033CD310 RAX=00000000A42C0000 RBX=00000000033CD310

RCX=0000000000200000 RDX=0000000000000001 R8=0000000020000000 R9=00007F74AC5953F8

R10=0000000000000000 R11=00000000383CCFEA R12=00000000033D43F0 R13=00000000033CD000

R14=00000000A42C0000 R15=0000000000000010

RIP=0000000000000000 GS=0000 FS=0000 RSP=00007F74ADD7DE98

EFlags=0000000000010606 CS=0033 RBP=00007F74C99ABFB0 ERR=0000000000000014

TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000

xmm0 0000000000000006 (f: 6.000000, d: 2.964394e-323)

xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)

xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)

xmm3 ffff000000000000 (f: 0.000000, d: -nan)

xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)

xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)

xmm6 40301c75619edf3c (f: 1637801728.000000, d: 1.611117e+01)

xmm7 3d763c8a7c010823 (f: 2080442368.000000, d: 1.263998e-12)

xmm8 40301c7598868ce6 (f: 2558954752.000000, d: 1.611117e+01)

xmm9 3feb07b5be32fda7 (f: 3191012864.000000, d: 8.446912e-01)

xmm10 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)

xmm11 bc565d22aa8ad7cf (f: 2861225984.000000, d: -4.849378e-18)

xmm12 3fc59ab8a15a52ed (f: 2707051264.000000, d: 1.687842e-01)

xmm13 3c62400000000000 (f: 0.000000, d: 7.914676e-18)

xmm14 3bb12609aede8ad0 (f: 2933820160.000000, d: 3.631354e-21)

xmm15 402fe2804e87b080 (f: 1317515392.000000, d: 1.594239e+01)

Target=2_90_20190417_286 (Linux 4.15.0-76-generic)

CPU=amd64 (32 logical CPUs) (0x1f720bc000 RAM)

----------- Stack Backtrace -----------

(0x00007F74C92954F2 [libj9prt29.so+0x3a4f2])

(0x00007F74C927A3B8 [libj9prt29.so+0x1f3b8])

(0x00007F74C929556E [libj9prt29.so+0x3a56e])

(0x00007F74C9295664 [libj9prt29.so+0x3a664])

(0x00007F74C927A3B8 [libj9prt29.so+0x1f3b8])

(0x00007F74C92953CB [libj9prt29.so+0x3a3cb])

(0x00007F74C997C784 [libj9vm29.so+0x9e784])

(0x00007F74C927A3B8 [libj9prt29.so+0x1f3b8])

(0x00007F74C997C9D6 [libj9vm29.so+0x9e9d6])

(0x00007F74C927963F [libj9prt29.so+0x1e63f])

(0x00007F74CB6AB890 [libpthread.so.0+0x12890])

---------------------------------------

JVMDUMP039I Processing dump event "gpf", detail "" at 2020/03/12 - please wait.

JVMDUMP032I JVM requested System dump using '/home/gs-40589/core.20200312.035350.6.0001.dmp' in response to an event

JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program. Attempting to rename either core or core.82.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 82 was not found. Expected to find core file with name "/home/gs-40589/core"

JVMDUMP032I JVM requested Java dump using '/home/gs-40589/javacore.20200312.035350.6.0002.txt' in response to an event

JVMDUMP010I Java dump written to /home/gs-40589/javacore.20200312.035350.6.0002.txt

JVMDUMP032I JVM requested Snap dump using '/home/gs-40589/Snap.20200312.035350.6.0003.trc' in response to an event

JVMDUMP010I Snap dump written to /home/gs-40589/Snap.20200312.035350.6.0003.trc

JVMDUMP007I JVM Requesting JIT dump using '/home/gs-40589/jitdump.20200312.035350.6.0004.dmp'

JVMDUMP010I JIT dump written to /home/gs-40589/jitdump.20200312.035350.6.0004.dmp

JVMDUMP013I Processed dump event "gpf", detail "".

**Comment by Janmm14** [comment] 2020-03-12 10:35
Duplicate of #1923 
Workaround provided: https://github.com/konsolas/AAC-Issues/issues/1923#issuecomment-597258738

**Closed by Janmm14** 2020-03-12 10:35 UTC
