### ISSUE TITLE
Names Duplicated Bug Still Happening

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#1252] opened 2018-03-03 02:05 UTC
The issue were the names of the players were getting multiplied by 100, is still happening, it is supposed to be already fixed, but its still happening

**Comment by Janmm14** [comment] 2018-03-03 03:14
Duplicate of #1239

3.3.11-b1 wasn't meant to fix that.

**Closed** 2018-03-03 03:15 UTC
Labels: 1. bug, 2. combat, 4. duplicate
