### ISSUE TITLE
Swimming in lava wont allow to go onto cake, etc...

### ISSUE THREAD

**Issue by johand199** [konsolas/AAC-Issues#459] opened 2017-02-19 14:32 UTC
Issue type (console error/false positive/bypass/other):
False Positive

Server version:
Spigot 1.8.8-R0.1-SNAPSHOT

ProtocolLib version:
4.2.0

AAC version:
AAC 3.0.4
 
ViaVersion version (if present):
1.0.3

A video proving the bypass/false positive if reporting a bypass/false positive:
https://youtu.be/cvUXCf3GN3g

**Comment by johand199** [comment] 2017-02-19 14:36
*update* It will flag you in water, but does not setback *update*

**Comment by CeIebrimbor** [comment] 2017-02-27 21:40
Labeling as unimportant....because well, how often are players swimming in lava up onto cake? Trying to prioritize the important issues.

**Comment by Photon-GitHub** [comment] 2017-04-02 17:57
I can no longer reproduce this and therefore close this as fixed.

**Closed by Photon-GitHub** 2017-04-02 17:57 UTC
Labels: bug, move, unimportant
