### ISSUE TITLE
Killaura Problem

### ISSUE THREAD

**Issue by MatinDark** [konsolas/AAC-Issues#1241] opened 2018-03-01 06:59 UTC
> [17:31:15 ERROR]: [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
> java.util.ConcurrentModificationException: null
>         at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_162]
>         at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:1.8.0_162]
>         at me.konsolas.aac.ah.onPacketReceiving(ah.java:63) ~[AAC.jar:3.3.11]
>         at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.0]
>         at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.0]
>         at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.0]
>         at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.0]
>         at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.0]
>         at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.0]
>         at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.0]
>         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [paper.jar:git-Paper-1335]
>         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [paper.jar:git-Paper-1335]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [paper.jar:git-Paper-1335]
>         at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [paper.jar:git-Paper-1335]
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [paper.jar:git-Paper-1335]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [paper.jar:git-Paper-1335]
>         at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [paper.jar:git-Paper-1335]
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [paper.jar:git-Paper-1335]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [paper.jar:git-Paper-1335]
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [paper.jar:git-Paper-1335]
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) [paper.jar:git-Paper-1335]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [paper.jar:git-Paper-1335]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [paper.jar:git-Paper-1335]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [paper.jar:git-Paper-1335]
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [paper.jar:git-Paper-1335]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [paper.jar:git-Paper-1335]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
> [17:31:15 ERROR]: Parameters:
>   net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInLook@1dbffe3a[
>     x=0.0
>     y=0.0
>     z=0.0
>     yaw=-94.95264
>     pitch=42.30007
>     f=true
>     hasPos=false
>     hasLook=true
>   ]
Server version: Paper Spigot 1.12.2

AAC version: 3.3.11

ProtocolLib version: latest

Plugin list: insert

Special environment information
ViaVersion version: latest (or N/A)

ProtocolSupport version: No (or N/A)

ViaBackwards version: No (or N/A)

BungeeCord plugins: Viaversion , premium vanish(or N/A)

**Comment by Janmm14** [comment] 2018-03-01 13:16
Duplicate of #1238

**Closed by Janmm14** 2018-03-01 13:16 UTC
