### ISSUE TITLE
TNT Boost issue reappeared

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#606] opened 2017-04-24 08:48 UTC
According to different reports, TNT Boosts are not working anymore.

**Comment by konsolas** [comment] 2017-04-25 16:51
Cannot reproduce.

**Comment by Janmm14** [comment] 2017-04-25 21:00
Genazt can reproduce

**Comment by CeIebrimbor** [comment] 2017-08-21 21:00
Closed in favor of #865

**Closed by CeIebrimbor** 2017-08-21 21:00 UTC
Labels: bug, move
