### ISSUE TITLE
StackOverflowError related to gson when executing some (probably most) AAC commands

### ISSUE THREAD

**Issue by Olexorus** [konsolas/AAC-Issues#2108] opened 2021-01-05 14:41 UTC
### Issue description
When I tried to run `/aac status`, it didn't give me any output but threw this exception:
```
[15:14:26] [Server thread/INFO]: Olexorus issued server command: /aac status
[15:14:26] [Netty Epoll Server IO #1/ERROR]: java.lang.StackOverflowError
[15:14:26] [Netty Epoll Server IO #1/WARN]: java.lang.StackOverflowError
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:566)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.stream.JsonWriter.beginArray(JsonWriter.java:287)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[15:14:26] [Netty Epoll Server IO #1/WARN]: 	at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
...
```
I tried to use `/aac reload` with the same result. `/aac spec` however worked. After this I restarted the server, which fixed the problem for now, but I'm assuming this'll happen again.

### Core information
**Server version**: git-Tuinity-"f06591a" (MC: 1.16.4) (most recent version of Tuinity as of writing this)

**AAC version**: 5.0.7

**ProtocolLib version**: v4.6.0-SNAPSHOT-b492 (downloaded today)

**Plugin list**: AAC5, AntiVPN, CMI, CoreProtect, DiscordSRV, FarmLimiter, LuckPerms, PacketLimiter, PlaceholderAPI, PremiumVanish, ProtocolLib, RedProtect, ViewDistanceTweaks, VillagerOptimiser, Votifier

### Special environment information
**ViaVersion version**: /

**ProtocolSupport version**: /

**ViaBackwards version**: /

**BungeeCord plugins**: /

### Configuration
Completely disabled mitigation and automatic kicks (I want AAC to be silent and only notify staff), I don't think anything else that's significant.

**Comment by konsolas** [comment] 2021-01-05 16:12
https://hub.spigotmc.org/jira/browse/SPIGOT-6012?focusedCommentId=38373&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38373

**Comment by Janmm14** [comment] 2021-01-06 15:57
I had the idea that gson's apparant loss of memory of the configured type adapters from bungee-chat might be caused by gson being loaded partly from another jar, causing potential hikkups of the jvm (maybe even some duplicated class loading in different modules or sth like that in later java versions).

It was found that DiscordSRV was used by both customers experiencing this problem and the one who got the error more often also had NuVotifier which also included not-relocated gson.

We suggested they remove com/google/gson folder from DiscordSRV and NuVotifier jars with a zip tool as temporary workaround and hope that the issue will not happen again to them in the next week or so.

**Comment by Janmm14** [comment] 2021-02-14 10:28
I'll close this issue for now.

**Closed** 2021-02-14 10:30 UTC
Labels: 1. error, 3. jar of many forks, 4. alt.-solution, 4. not-a-bug
