### ISSUE TITLE
False fly detention when using ladders with trap doors.

### ISSUE THREAD

**Issue by raidmax21** [konsolas/AAC-Issues#486] opened 2017-03-12 00:15 UTC
False fly detention when using ladders with trap doors.

If you create a ladder and place a trap door above it, once you pass thought the trap door or sit there, you will get flagged by AAC for flying.

Players sometimes put trap doors above ladders to close off levels of a base or house. When a player has a lot of floors close together, they will pass though a lot of trap doors and rack up a very high VL lvl depending on what you set your your min VL too. https://i.gyazo.com/f06638b37f432b873c3bc927bfa73620.png

For example, one of our worlds if a building world, that is quite large and runs from 10-20tps with pvp disabled. This world has most of the checks disabled due to the odd TPS and as a result we have our min VL lvl on flying set to 1000 with our ban VL level also set to 1000. This allow players to fly without them knowing they are getting flagged. After a 5-10 sec of flying, the player hits vl 1000 and is banned. Because we have no min VL lvl rubber banding back to the ground, the can pass the trap doors and get a super high vl.

On our PVP world, we have a much tighter system since it's a 19.5/20 tps server. At first the player can pass the ladder and gain some VL but after they flagged, they start to rubber band to the ground and cannot pass the trap door. Here is that scenario: https://i.gyazo.com/e6f0eaa69ed7b95760737e2679093727.mp4

The player we tested this with is called shhiit. It's a player name from a hack client.
Here is an extreme version: https://i.gyazo.com/ace15b575f053c20d60fb30209642d45.mp4

Server version: 1.10.2-r0.1
AAC: 3.0.5
ProtocolLib: 4.2.0
ViaVersion: 1.0.4
Bungee: https://gyazo.com/c6555cac4eb5878acbd6239c5ebfe1c2.png

**Comment by CeIebrimbor** [comment] 2017-03-12 00:18
We just skipped right past AAC v4.0 and went right on to v5.0!

**Comment by raidmax21** [comment] 2017-03-12 01:27
Edited lol...

Looks like that field was from another entry but I'm not sure what.

**Comment by Janmm14** [comment] 2017-03-12 22:27
Which client version was used? Can't reproduce in 1.8

**Comment by raidmax21** [comment] 2017-03-15 17:40
You first need a VL lvl.

This was tested by looking at all the VL's from the logs of of all the players and they were all coming from then ladders with the trap doors..

It was also confirmed by my mate on 1.1

**Comment by Photon-GitHub** [comment] 2017-04-02 18:05
I can no longer reproduce this and therefore close this as fixed.

**Closed by Photon-GitHub** 2017-04-02 18:05 UTC
Labels: bug, move
