### ISSUE TITLE
IllegalStateException on PlayerMoveEvent: Start blocked missed in BlockIterator

### ISSUE THREAD

**Issue by Supereg** [konsolas/AAC-Issues#273] opened 2016-12-25 18:49 UTC
Player joined the server and start walking. The following exception was printed three times.
http://imgur.com/a/te8SX

**Comment by geNAZt** [comment] 2016-12-26 08:32
What server software do you use?

**Comment by Supereg** [comment] 2016-12-26 09:26
Normal Spigot 1.8
Latest Aac3 release

**Comment by konsolas** [comment] 2016-12-26 10:09
BlockIterator (upon further testing) appears to throw IllegalStateException in perfectly normal locations, such as a falling into the void and when above the build height of 256.

I am uncertain about what is meant by "start walking", however. Did the player spawn at 257 blocks?

**Comment by konsolas** [comment] 2016-12-28 11:01
Closing as duplicate of #288 because it has more information than this.

**Closed by konsolas** 2016-12-28 11:01 UTC
Labels: duplicate, error
