### ISSUE TITLE
Could not pass event PlayerMoveEvent: Console Spam

### ISSUE THREAD

**Issue by xGodly** [konsolas/AAC-Issues#487] opened 2017-03-12 02:42 UTC
Could not pass event PlayerMoveEvent:

Error: http://pastebin.com/KYwRG7SH

**Server version**: 1.11

**AAC version**: 3.0.5-B1

**ProtocolLib version**:  #newest

**Plugin list**: http://prntscr.com/eivi0m

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: 4.25

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Justinis77** [comment] 2017-03-15 14:40
me too ...

**Comment by marint94** [comment] 2017-03-18 10:11
me too

**Comment by Janmm14** [comment] 2017-03-21 21:33
closing as duplicate of #492 (i know that issue was reported later on)

**Closed by Janmm14** 2017-03-21 21:33 UTC
Labels: error
