### ISSUE TITLE
[AAC 3.2.1+] Fly/badpackts setback glitch => vclip (Semi-Godmode)

### ISSUE THREAD

**Issue by GeoGamerLP** [konsolas/AAC-Issues#914] opened 2017-08-29 21:56 UTC
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: insert

**AAC version**: insert

**ProtocolLib version**: insert

**Plugin list**: insert

### Special environment information
**ViaVersion version**: insert (or N/A)

**ProtocolSupport version**: insert (or N/A)

**ViaBackwards version**: insert (or N/A)

**BungeeCord plugins**: insert (or N/A)

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by CeIebrimbor** [comment] 2017-08-29 22:05
No effort made to make an actual issue with info. Based on title (only info given), it sounds like a dupe of #899

**Closed by CeIebrimbor** 2017-08-29 22:05 UTC

**Comment by GeoGamerLP** [comment] 2017-08-29 22:07
@CeIebrimbor I accidentally pressed enter when writing the issue. Please reopen this.

**Comment by CeIebrimbor** [comment] 2017-08-29 22:08
> @CeIebrimbor I accidentally pressed enter when I wrote the issue. Please reopen this.

Is it a duplicate of the linked issue above? (falling through blocks after a teleport and Fly setback)

**Comment by GeoGamerLP** [comment] 2017-08-29 22:10
> Is it a duplicate of the linked issue above? (falling through blocks after a teleport and Fly setback)
No. #899 happens randomly and only has to do with the fly detection while my issue is intenionally triggered and involves the badpackets check too

**Comment by CeIebrimbor** [comment] 2017-08-29 22:13
I am aware that you are reporting the fact that it can be used as a secret underground bunker. But it is the same bug. The main report is reported as an annoying bug, but that does not mean it's not the same bug.
