### ISSUE TITLE
Speed FP

### ISSUE THREAD

**Issue by DasCanard** [konsolas/AAC-Issues#1296] opened 2018-03-14 11:05 UTC
### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.12

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC, ProtocolLib

Video: https://streamable.com/yo642
Jump to the Edge of the Block

**Comment by Rerd** [comment] 2018-03-14 12:13
Duplicate of #1231.

**Comment by DasCanard** [comment] 2018-03-14 12:15
@Rerd sorry i dont saw it

**Closed** 2018-03-14 12:15 UTC
Labels: 1. bug, 2. move
