### ISSUE TITLE
Velocity detection not workign when standing still v3.6.4

### ISSUE THREAD

**Issue by MeowMiaoMiao** [konsolas/AAC-Issues#1543] opened 2018-11-17 18:21 UTC
server version: 1.8.9
aac version: 3.6.4
plib version: 4.1
The version after AAC3.5.0-b1 has this problem

liquidbounce b58 
![12](https://user-images.githubusercontent.com/29674595/48664353-597d0080-ead8-11e8-9236-b624a2f80aa3.jpg)

**Comment by Janmm14** [comment] 2018-11-17 19:05
Cannot reproduce.

**Comment by MeowMiaoMiao** [comment] 2018-11-18 13:34
> Cannot reproduce.
> 
> What do you mean with
> 
> > The version after AAC3.5.0-b1 has this problem
> 
> when you just wrote
> 
> > aac version: 3.6.4
> > ?

Same velocity configuration 

AAC 3.5.0-b1
![12321](https://user-images.githubusercontent.com/29674595/48673168-96e59a80-eb79-11e8-950c-fa10d2d8da5f.gif)




AAC 3.6.4
![12322](https://user-images.githubusercontent.com/29674595/48673157-787f9f00-eb79-11e8-9c12-c6fcc6015345.gif)
It doesn't seem to work.

**Comment by Janmm14** [comment] 2018-11-18 21:13
Try enabling verbose and give yoursefl aac.verbose permission please.
Also make sure you actually used mode simple.

**Comment by MeowMiaoMiao** [comment] 2018-11-19 04:34
> Try enabling verbose and give yourself aac.verbose permission please. Does it show velocity detection?
> 
> I tried it with exactly your setup (because it was mine) and it was detected.

It seems to detection only when the target player is not moving.
![12324](https://user-images.githubusercontent.com/29674595/48686486-2c733f80-ebf7-11e8-9c96-7193657d4824.gif)
![afk](https://user-images.githubusercontent.com/29674595/48686487-2c733f80-ebf7-11e8-9b61-b9caeac66a4a.gif)

**Comment by Janmm14** [comment] 2018-12-25 19:05
Related to move event not happening when player is not moving / rotating head. Not an issue if enemy is fighting back.

**Comment by Janmm14** [comment] 2018-12-25 19:09
Something weird going on here. Marking as critical, because it could be an issue of the system.

**Closed** 2019-07-20 17:43 UTC
Labels: 1. bypass, 2. move, 3. critical, 3. recheck newest version
