### ISSUE TITLE
Flying hack issue

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#285] opened 2016-12-26 11:58 UTC
when people try to tame a animal like a horse donkey, im getting a message that they will be kicked for fly hacking

just reporting what i see

**Comment by Rqcco** [comment] 2016-12-26 12:41
I don't get any violations when reenacting this. Is this a bug on 1.8 or 1.10? Also, make a video, need more information.

**Comment by Janmm14** [comment] 2016-12-26 14:46
It would be nice if you give additionally these informations:

- server version
- client version
- usage of viaversion or protocolsupport
- if applicable bungeecord version & it's plugins

**Comment by AmazedMender16** [comment] 2016-12-26 14:59
server version: 1.11.2 Latest build
client version: 1.11.2
viaversion: latest version
No Bungeecord

**Comment by Janmm14** [comment] 2016-12-26 17:58
@AmazedMender16
Why are you using ViaVersion on a 1.11.2 server? Thats pointless.

**Comment by konsolas** [comment] 2016-12-28 11:02
Closing - cannot reproduce and no info provided.

**Closed by konsolas** 2016-12-28 11:02 UTC
Labels: bug, cannot reproduce, insufficient info
