### ISSUE TITLE
Nuker

### ISSUE THREAD

**Issue by EvilLord1323** [konsolas/AAC-Issues#2136] opened 2021-01-19 09:55 UTC
https://youtu.be/EcB-mm1emhg

Server version: 1.12.2

AAC version: AAC 5.0.8

ProtocolLib version:
4.5.1

Plugin list: plugins don't interfer

ViaVersion version: 3.2.1

BungeeCord plugins: plugins don't interfer

Configuration
Celebrimor

**Comment by konsolas** [comment] 2021-01-21 12:55
Duplicate of #2126

**Closed by konsolas** 2021-01-21 12:55 UTC
Labels: 2. world/interact
