### ISSUE TITLE
bug fastplace/nuker

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#286] opened 2016-12-26 12:39 UTC
Antycheats no detect fastplace and nuker sorry for my bad English. Fastplace detects when huzuni set to 2+ and nukers not detect at all. Huzuni 1.8 / 1.10.2

**Comment by Rqcco** [comment] 2016-12-26 12:44
This is not enough information. (What version, how do you reproduce it, video?) for a Are you sure you have AAC setup correctly?

**Comment by ProDash1998** [comment] 2016-12-26 15:33
version 3.0 and 1.9.10-b8

**Comment by ProDash1998** [comment] 2016-12-26 15:34
The video later because currently I'm doing reinstall the system

**Comment by konsolas** [comment] 2016-12-28 15:35
Seeing as both are blocked and there are no problems with the detection of fastplace/nuker, closing due to insufficient info.

**Closed by konsolas** 2016-12-28 15:35 UTC
Labels: insufficient info

**Comment by ProDash1998** [comment] 2016-12-28 16:37
Upload video paste it here soon
