### ISSUE TITLE
Alot False Positives found

### ISSUE THREAD

**Issue by guerryer** [konsolas/AAC-Issues#546] opened 2017-04-09 08:23 UTC
Here is some False Positives found on the AACv3 Official Test Server (1.8.8)
Date 2017-04-09

- [x] https://youtu.be/sGnJXF6zC88 - Speed 

- [x] https://youtu.be/bj0I4X7S4S0 - Speed / Fly

- [x] https://youtu.be/OpuszywYFtU - Fly

- [x] https://youtu.be/m2FD-Ai3ybk - Fly

- [x] https://youtu.be/LhiCyeNH-Ls - Fly

- [x] https://youtu.be/OqqsMaw8xBY - Fly

- [x] https://youtu.be/8lJCs1NzM3w - Phase / Fly / Speed

- [x] https://youtu.be/mhZ4zpcyCx4 - Fly

Additional Informations
- You can get false kick for all false positives show in this list.
- Minecraft Version use 1.8.9-OptiFine_HD_U_H7

Playlist : https://www.youtube.com/playlist?list=PLItmJx6Tis9KPa9zRtxh-ArmznVSCVY7e

**Comment by nur1popcorn** [comment] 2017-04-09 16:45
GUWERERYYER

**Comment by konsolas** [comment] 2017-04-15 11:16
@guerryer I can't reproduce number 4, can you give more information? 

Ticking these off as they're fixed in local builds.

**Closed** 2017-04-15 15:32 UTC
Labels: bug, move

**Comment by guerryer** [comment] 2017-04-15 19:46
The number 8 is not fixed. (tested on the test server)
