### ISSUE TITLE
Climbing a water or lava stream flags for Jesus

### ISSUE THREAD

**Issue by Teriuihi** [konsolas/AAC-Issues#1370] opened 2018-04-29 19:50 UTC
### Issue description

When a player is swimming up the corner of a vertical water or lava stream starting from the inside water or lava they get flagged for Jesus hacks.

To reproduce the issue make a 5*5 water lake with a water pillar (10 blocks or higher) in the middle. Swim up the stream as far in the corner as possible. This works with lava as well in exactly the same way.

### Core information
**Server version**: 1.12.2

**AAC version**: 3.3.14

**ProtocolLib version**: 4.4.0

**Plugin list**: http://prntscr.com/jbp7vk

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: 

N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: N/A

### Configuration
Using Celebrimors ghost config

**Comment by Minemaniak** [comment] 2018-04-30 12:39
Duplicate of https://github.com/konsolas/AAC-Issues/issues/1171 @Janmm14

**Comment by Janmm14** [comment] 2018-04-30 13:29
Thx

**Closed by Janmm14** 2018-04-30 13:29 UTC
Labels: 1. bug, 2. move, 4. duplicate
