### ISSUE TITLE
Teleports via plugins trigger the speed check

### ISSUE THREAD

**Issue by alexmarkey** [konsolas/AAC-Issues#1046] opened 2017-10-26 22:44 UTC
### Issue description
We are running Minigames on our network.  Players spawn in a lobby and when the game begins they all get teleported to their spawnpoints in the Minigame.  Upon teleporting, they occasionally trigger the speed check and get kicked.
I have also noticed this when players respawn after dying, they trigger the Speed check and get kicked.

### Core information
**Server version**: 1.8.9

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC and Minigame plugin (2 plugins)

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Cels config

**Comment by CeIebrimbor** [comment] 2017-10-26 22:49
Detection logs? Maybe a dupe of #1035?

**Comment by Justinis77** [comment] 2017-10-27 19:34
yes this is a dupe of 1035

**Comment by Justinis77** [comment] 2017-10-27 19:35
geNAZt reportet this for me, this is on my Network too

**Comment by MadMageKefka** [comment] 2017-11-20 01:40
Failed speed checks also hapoen on my server (spigot 1.12.2) when any player with high ping teleports via any means, if that info helps at all.

**Comment by Janmm14** [comment] 2017-11-20 08:01
Latest AAC version?

**Comment by MadMageKefka** [comment] 2017-11-20 09:23
Yes

**Comment by CeIebrimbor** [comment] 2017-11-20 15:20
I have now started experiencing this. Teleport by command block and command seems to be fine, but plugin teleports are getting messed up.

Where I have noticed it primarily is group teleports at the start/end of events. Players get left behind regularly. I think this may have been reported elsewhere on the tracker.

**Closed** 2018-01-20 15:28 UTC
Labels: 1. bug, 2. move, 4. fixed
