### ISSUE TITLE
FastBreak False Positives - Harvesting Netherwart From Minecart

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2185] opened 2021-02-23 16:10 UTC
Users are reporting getting kicked while harvesting netherwart from a Minecart.
This is a very popular method of farming on our server.
https://pastebin.com/raw/c0Au5yCr

### Core information
**Server version**: 1.16.5 (Paper Build 484)

**AAC version**: 5.0.11

**AAC config**: 5.0.11|1-Default-Celebrimbor

**AAC enabled checks**: The following checks are disabled & altered:
delays.fast_place: false
aimbot.enabled: false
hitbox.enabled: false
features.aac_interact_place: 0

**ProtocolLib version**: 4.6.0 Build 495

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment] 2021-02-23 16:26
Need debug logs of this issue.

**Comment by konsolas** [comment] 2021-02-23 16:28
Also for some reason the actual player analysis is missing from the logs after this line:

```
Line 28083: [09:44:41] [Server thread/INFO]:  AAC probablydead - Spectate
	Line 28084: [09:44:41] [Server thread/INFO]:  AAC Player Analysis of probablydead at 23 Feb 2021, 09:44
```

**Comment by andrewkm** [comment] 2021-02-23 16:54
These are all the logs AAC presented us with in the console.
You removed all the great logging information we had in AAC 4, how are we to provide more information?

**Comment by andrewkm** [comment] 2021-02-23 16:56
Hm, is this what you're talking about:
https://pastebin.com/raw/c0Au5yCr

**Comment by konsolas** [comment] 2021-02-23 16:58
`features.aac_interact_break.weight` -> 0 will stop the kicks until the issue is fixed on the plugin side

**Comment by andrewkm** [comment] 2021-02-23 16:59
Thanks!

**Comment by Janmm14** [comment] 2021-02-23 20:21
To create a debug log, enable it for you with the command `aac debug yourplayername` (possible in console).
Debug for yourplayername will be printed to where you executed the command.
Then do the action which causes the flagging.
Disable debug logging with the same command.

Not sure tho if konsolas still needs a debug log.

**Comment by andrewkm** [comment] 2021-04-03 20:57
@konsolas  @Janmm14 
Can you please remove insufficient label as the relevant information was provided. :)

Or are you still looking for something else?

**Comment by andrewkm** [comment] 2021-09-30 02:39
Plugin abandoned.

**Closed** 2021-09-30 08:51 UTC
Labels: 1. bug, 2. world/interact
