### ISSUE TITLE
Speed/Fly false positive certain slab angles

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#316] opened 2016-12-30 01:23 UTC
Jumping into the slabs at a certain angle causes for false fly/speed flags, I was only able to replicate this issue on 1.11.

https://youtu.be/w0tOBpwjUpw

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.0

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by Rqcco** [comment] 2016-12-30 03:39
#284

**Comment by Rqcco** [comment] 2017-03-05 05:05
I can't reproduce this on the test server (v3.05, possibly patched?) . I'm going to close it and if it's still an issue feel free to reopen.

**Closed by Rqcco** 2017-03-05 05:05 UTC
Labels: bug, compatibility, move
