### ISSUE TITLE
AAC Version Update ERror

### ISSUE THREAD

**Issue by Cynamic** [konsolas/AAC-Issues#1039] opened 2017-10-21 20:53 UTC
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: 1.8.8

**AAC version**: AAC 3.3.4

**ProtocolLib version**: idk

**Plugin list**: aac and bw

### Special environment information
**ViaVersion version**: insert (or N/A)

**ProtocolSupport version**: insert (or N/A)

**ViaBackwards version**: insert (or N/A)

**BungeeCord plugins**: insert (or N/A)

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

[22:44:36] [Thread-56/INFO]: [AAC] A new version of AAC is available!
[22:44:36] [Server thread/WARN]: [AAC] Task #23 for AAC v3.3.4 generated an exception
java.lang.NullPointerException
    at me.konsolas.aac.y.lambda$new$0(y.java:2) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[BedWars2x131018.jar:git-PaperSpigot-"8b18730"]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [BedWars2x131018.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [BedWars2x131018.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [BedWars2x131018.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [BedWars2x131018.jar:git-PaperSpigot-"8b18730"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [BedWars2x131018.jar:git-PaperSpigot-"8b18730"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[22:44:36] [Thread-56/WARN]: [AAC] Logger functionality has been disabled in the configuration file.

hope for help

**Comment by Slimerblue22** [comment] 2017-10-21 22:16
...Have you tried updating AAC?

**Comment by Photon-GitHub** [comment] 2017-10-21 22:51
Please don’t just post „idk“ as your ProtocolLib version, instead fill in the information the template requests.

**Comment by Janmm14** [comment] 2017-10-21 22:53
Likely a duplicate of #1028

**Comment by Toshka17** [comment] 2017-10-23 17:42
I understand that this is the same thing.
Endless spam of this error: https://pastebin.com/4qC8Rc2i

**Comment by konsolas** [comment] 2017-10-24 09:31
Closing due to insufficient information.

**Closed by konsolas** 2017-10-24 09:31 UTC
Labels: 1. error, 3. insufficient info, 4. inactivity
