### ISSUE TITLE
AAC randomly crashing the server

### ISSUE THREAD

**Issue by IceString3** [konsolas/AAC-Issues#951] opened 2017-09-11 23:32 UTC
### Issue description
The crashes seem to happen at random times. The Server Thread mentions AAC, so I guess AAC is likely the culprit.

Server thread dump: https://gist.github.com/IceString3/882c9ef84604f7b7e2b3b0f06fa482d3

### Core information
**Server version**: Paper version git-Paper-1201 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.3.2-b2

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC, AACHider, AntiCommandTab, antiraildupe, AuthMe, AuthMeBridge, BlocksHub, BungeePortals, BungeeSuiteWarps_1.9, BungeeTabListPlus, ConditionalCommands, ConsoleSpamFix, CoreProtect, DiscordSRV, FastAsyncWorldEdit, GriefPrevention, Hibernate, LimitedCreative, LiteBans, LuckPerms, MelonDamageLib, MineSecure, MyHome, OpenInv, PandaWire, ProtocolLib, React, Reloader, RewardVoting, RTP, SafeArmorStands, SetSpawners, SharpSK, SilkSpawners, Skellett, SkinsRestorer, SkQuery, skRayFall, Skript, SkStuff, TuSKe, Vault, ViaBackwards, ViaVersion, Votifier, WorldEdit

### Special environment information
**ViaVersion version**: 1.2.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.2.0

**BungeeCord plugins**: BungeeAuthMeBridge-1.6.2, BungeeStaffChat-1.5.4, BungeeSuite-1.9, BungeeTabListPlus-2.6.4, EMPBungee, LuckPerms-Bungee-3.2.58, nuvotifier-universal-2.3.3, SkinsRestorer-v13.1.3

### Configuration
Using Celebrimbor's config

**Comment by CeIebrimbor** [comment] 2017-09-12 00:38
Is there a specific lead up or replicable event leading to this? Possibly to do with moving to unloaded chunks?

Or is the occurrence 100% unknown and random (can happen right after server start or 13 hours after)?

**Comment by IceString3** [comment] 2017-09-12 01:10
It can happen at any time. However, after close inspection of the server logs and AAC logs, it seems like a server hang. The last command before the hang is always /spawn. And the last check before the hang is the Fly one, shown like this: EBoyGamer failed Fly: moved unexpectedly: -0.0980 (0.4200->0.3332 / -n-n16) [ping:97 tps:20.0] VL:67

**Comment by CeIebrimbor** [comment] 2017-09-12 02:53
Please add any more discoveries that pop up. Not sure this is enough to go off.

**Comment by FlexVN** [comment] 2017-09-12 11:12
https://hastebin.com/oqurikuneq.vbs
to crash :(

**Comment by FlexVN** [comment] 2017-09-12 11:12
AAC 3.3.2-b2 is crash

**Comment by Janmm14** [comment] 2017-09-12 13:56
It looks like your server has two server threads running - what is going on there?

**Comment by FlexVN** [comment] 2017-09-12 15:28
sorry you
My permissionEX failed and caused lag 🥇

**Comment by gardenGnostic** [comment] 2017-09-12 20:44
Hello, I own the community that OP is posting about, and I'd like to add some info on to the original Issue. 
The server crash occurs only when we use AAC version 3.3.1 to 3.3.2-b2, and have Fly Check enabled.

Spigot gives same crash, not just Paper. here is a thread dump while using Spigot: https://pastebin.com/kL2ugP9J

It seems to always occurs after a player teleports. /spawn and /home, does not matter the method. New chunk rendering is likely not the cause. A few specific locations can trigger it more than others, but nothing out of the ordinary. Server does not necessarily have to be running for an extended period of time to use memory overhead (we had a crash after just 15 minutes of uptime).

**Comment by CeIebrimbor** [comment] 2017-09-13 03:52
I've seen 3 individual cases of this so far.

**Comment by Janmm14** [comment] 2017-09-17 14:00
I am wondering how AAC can cause getting chunk information to last that long.

**Comment by konsolas** [comment] 2017-10-12 18:54
Similar to #1002, fixed in the same way.

**Closed** 2017-10-12 20:15 UTC
Labels: error, move
