### ISSUE TITLE
SetBack when gliding out of a waterfall

### ISSUE THREAD

**Issue by Supereg** [konsolas/AAC-Issues#263] opened 2016-12-16 18:27 UTC
Video material: https://youtu.be/0rduwj0EkNc
was tested on 1.8 test server

got some other setbacks when jumping and climbing ladders, got kicked for criticals o.O

**Comment by Rqcco** [comment] 2016-12-16 20:59
Duplicate of #196

**Closed** 2016-12-16 21:00 UTC
Labels: bug, duplicate
