### ISSUE TITLE
Custom Weapons made by any plugin.

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#1193] opened 2018-02-08 15:49 UTC
### Issue description
We need a way to allow custom weapons made by other plugins to allow extra speed or extra with that weapon/item, you are limiting servers with stopping this use.

### Core information
**Server version**: 1.12.2 Paper Spigot 1320

**AAC version**: 3.3.9

**ProtocolLib version**: 4.4.0 b390

**Plugin list**: MythicMobs to create items, or Essentaials to create items that when held create more speed, here is an example. https://i.imgur.com/1QutmVD.png

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: LuckPerms

### Configuration
I use the paid config.

**Comment by Janmm14** [comment] 2018-02-08 16:24
The compatibility list in the overview states AAC is incompatible with item attributes.

Duplicate of #206

**Closed by Janmm14** 2018-02-08 16:24 UTC

**Comment by FrozenBeard** [comment] 2018-02-08 16:27
@Janmm14 Which is why its being requested, as its a massive pitfall. People keep requesting it, people want it fixed.

**Comment by Janmm14** [comment] 2018-02-08 16:54
I know, still there is already issue 206
