### ISSUE TITLE
Sneak + Block on head = Phase (1.11.2)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#381] opened 2017-01-21 19:28 UTC
https://youtu.be/Esr0Uzmk9B0

~~Jump on tip of block = fly~~
Sneak jump = phase

Edit: The Phase happens regardless of location. If you sneak and bump a block, it is Phase. This includes ladders while sneaking.
https://youtu.be/ox0meZHuD-s

PaperSpigot 1.11.2
AAC 3.0.2
ProtLib 4.2.1

No Protocol Hacks or special conditions.
Plugins: AAC, Protlib and Permissions

**Comment by Janmm14** [comment] 2017-01-22 00:34
sneaking does actually start lowering your hitbox somewhere between 1.8 and 1.11 clients. I know that I found out this specific issue about a month ago and it got fixed, maybe it came back.

**Comment by CeIebrimbor** [comment] 2017-01-22 16:34
Fly when jumping fixed. Phase when sneaking and touching block above = Phase. Whether it be via ladder or jump.

**Comment by Photon-GitHub** [comment] 2017-04-02 17:20
I cannot reproduce this anymore, therefore I will close this as fixed.

**Closed by Photon-GitHub** 2017-04-02 17:20 UTC
Labels: bug, move
