### ISSUE TITLE
 Could not pass event PlayerInteractEvent to AAC v3.5.0

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1484] opened 2018-08-18 16:06 UTC
### Issue description

Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: insert paper spigot 1.12.2

**AAC version**: insert 3.5.0-b1

**ProtocolLib version**: insert latest

**Plugin list**: insert

### Special environment information
**ViaVersion version**: insert (or N/A) i don't use it

**ProtocolSupport version**: insert (or N/A)  
ProtocolSupport 4.28

**ViaBackwards version**: insert (or N/A) i don't use it

**BungeeCord plugins**: insert (or N/A)

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 
downlaod log, open with notepad:
https://drive.google.com/open?id=1A08h2NzdZKgXofnYJresaifpKRfdj8PB

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by Photon-GitHub** [comment] 2018-08-21 03:10
Duplicate of #1483

**Closed by Photon-GitHub** 2018-08-21 03:10 UTC
Labels: 1. error
