### ISSUE TITLE
AAC Jump Potion False Positives

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#447] opened 2017-02-12 13:24 UTC
Jump Potion False Positives.

Console:
[13:37:20 INFO]: [AAC] [CONSOLE] MinecraftTR is suspected for Fly (ping = 0, tps = 19.73)
[13:37:52 INFO]: [AAC] [CONSOLE] MinecraftTR is suspected for Fly (ping = 1, tps = 18.92)
[13:38:22 INFO]: [AAC] [CONSOLE] MinecraftTR is suspected for Fly (ping = 0, tps = 19.5)

Video Link: https://youtu.be/628rESlSXt0

Server version: 1.8.8

AAC version: 3.0.3

ProtocolLib version: 4.2.0+

Plugin list: AAC, ProtocolLib

ProtocolHack Support: None

ViaVersion: None

Other: None

**Comment by Photon-GitHub** [comment] 2017-02-12 14:40
Please update to 3.0.4

**Comment by Pluginsel** [comment] 2017-02-16 13:03
Tested on 3.0.4 version and working again, waiting for fixing...

**Comment by konsolas** [comment] 2017-02-19 16:06
Can't reproduce this one on the default config.

**Comment by Pluginsel** [comment] 2017-02-19 16:32
I am using default config, http://pastebin.com/mC3prbsB

**Comment by Janmm14** [comment] 2017-02-24 18:20
@konsolas reproducible on the official 1.8 test server

**Comment by Photon-GitHub** [comment] 2017-04-02 17:50
I can no longer reproduce this and therefore close this as fixed.

**Closed by Photon-GitHub** 2017-04-02 17:50 UTC
Labels: bug, move
