### ISSUE TITLE
Console error - [AAC5] Unhandled exception number 256 occured in onPacketSending(PacketEvent) for AAC5

### ISSUE THREAD

**Issue by akosvr** [konsolas/AAC-Issues#2139] opened 2021-01-23 00:36 UTC
ProtocolLib 4.5.1
paper-1.16.5 #439
AAC 5.0.9

[01:16:34 ERROR]: [AAC5] Unhandled exception number 256 occured in onPacketSending(PacketEvent) for AAC5
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.events.PacketContainer.getSectionPositions()'
        at me.konsolas.aac.bf.b(bf.java:196) ~[?:?]
        at me.konsolas.aac.b9.a(b9.java:89) ~[?:?]
        at me.konsolas.aac.e7.a(e7.java:3) ~[?:?]
        at me.konsolas.aac.timings.AACListener.onPacketSending(AACListener.java:34) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1709) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:499) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:427) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:822) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:816) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:734) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:460) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-439]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Janmm14** [comment] 2021-01-23 02:34
Duplicate of #2135, see here how to fix: https://github.com/konsolas/AAC-Issues/issues/2135#issuecomment-762794935

**Closed by Janmm14** 2021-01-23 02:34 UTC
