### ISSUE TITLE
Block edge false positive when jumping near a wall.

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#104] opened 2016-10-30 20:12 UTC
If you jump off a edge of a block (a helping-jump is very useful here) you will get flagged for fly.
This only happens if you are sneaking in the right or left corner of a block and not if you are jumping off in the middle.
It will flag you for normalmovements (probably parkour), can kick you and it will drag you down.
(If you have problems with the reproduction please message me.)

**Comment by konsolas** [comment] 2016-10-30 21:34
NormalMovements is not a check in AAC v3. Where was this tested?

**Comment by konsolas** [comment] 2016-10-30 22:53
I'm going to close this as cannot reproduce. No edge jumps have yielded any results, and normalmovements is not a thing.

**Comment by Photon-GitHub** [comment] 2016-10-30 23:03
This is tested on the test server please join if you want to see it.

**Comment by Photon-GitHub** [comment] 2016-10-30 23:05
I described it as NormalMovements as it detects me like the former NormalMovements check

**Comment by Photon-GitHub** [comment] 2016-10-30 23:16
Video incoming...

**Comment by Rqcco** [comment] 2016-10-30 23:20
https://www.youtube.com/watch?v=VFLO1rsynM0

**Comment by konsolas** [comment] 2016-11-14 18:14
Update: this works on any block edge, but only if it is = 1 block away from a wall. 

Will remove the "critical" label as the situation in question works only with certain jump strategies and in a specific built location.

**Comment by konsolas** [comment] 2016-11-19 14:19
@Photon-GitHub needs confirmation from you.

**Comment by konsolas** [comment] 2016-12-03 18:47
Will close this one as fixed.

**Closed by konsolas** 2016-12-03 18:47 UTC
Labels: bug, planned
