### ISSUE TITLE
Sometimes AAC cancels teleport event

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#667] opened 2017-05-18 03:53 UTC
### Issue description

I'm using AAC for a minigame server, and some player are not teleported to certain spawn position when the minigame changes round. Players are in spectator mode, when the minigame change round, their gamemode is changed to adventure and teleport to the spawn in the same tick. Currently I can't replicate this.

Console logs (you can see player Chidung saying "bug spawn"): https://pastebin.com/81E8y35S
AAC logs: https://pastebin.com/yeqRUrRi
The exact time when this happened is 9:36:36

### Core information
**Server version**: PaperSpigot 1.11.2

**AAC version**: 3.1.6 b2 (3.1.6 b4 currently have too many teleport issues)

**ProtocolLib version**: 4.2.2-SNAPSHOT-b357

**Plugin list**: upon request

### Special environment information

**ProtocolSupport version**: 4.26

**BungeeCord plugins**: upon request

**Comment by geNAZt** [comment] 2017-05-18 11:56
https://github.com/konsolas/AAC-Issues/issues/656

**Comment by campzazathelord** [comment] 2017-05-18 13:30
same

**Comment by andrewkm** [comment] 2017-05-18 19:30
Same issue here.

My inquiry in the AAC discord:

Hey @konsolas ,

We are having an issue with one of our plugins (a custom SG we wrote) not teleporting the player at the end of the match. We are doing it via player.teleport(dmSpot) and changed it to player.teleport(dmSpot, PlayerTeleportEvent.TeleportCause.PLUGIN) in attempt to fix it, but it did not work.

Occasionally the following stack appears when it happens (it happens once every 3 games or so): https://pastebin.com/raw/55keLXJ1

When it did happen the AAC logs showed this issue for the player who was prevented from teleportation: https://pastebin.com/raw/Uib6GqfV

It all started giving us issues (our plugin teleporting players) since we switched to AAC. Either we are doing something wrong on our end, something is up with AAC, or we need to adjust our AAC config.

Can you perhaps shed some light and point us in the right direction? (Maybe we should attempt to make use of the AAC developers API?)

**Comment by CeIebrimbor** [comment] 2017-05-18 21:06
Dupe of #656

**Closed by CeIebrimbor** 2017-05-18 21:06 UTC
