### ISSUE TITLE
Major problem  Server doesn't respond

### ISSUE THREAD

**Issue by JavituRec** [konsolas/AAC-Issues#904] opened 2017-08-27 11:19 UTC
### Issue description
The server doesn't respond in start
The error: https://hastebin.com/isivitedum.md

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.1-b1

**AACAditionPro version**: 3.2.2

**ProtocolLib version**: 4.3.0

**Plugin list**: 
![pl12346ghj](https://user-images.githubusercontent.com/10663192/29749386-3d405e30-8b2a-11e7-8ee9-e140819ab18f.png)

### Special environment information
**ViaVersion version**: LAST

**Comment by CeIebrimbor** [comment] 2017-08-27 19:17
Can you try ProtocolLib 4.2.0?

**Comment by Janmm14** [comment] 2017-08-27 21:10
Do you have a debugger attached (unsupported)?
Which JVM version are you using (try updating)?

**Comment by JavituRec** [comment] 2017-08-28 23:47
Yes but this problem only occurred once. I have been reviewing the console and found other errors while the server was online.

1.- https://hastebin.com/yeburikidi.sql
2.- https://hastebin.com/filolulaqo.vbs

**Comment by Janmm14** [comment] 2017-08-29 08:07
Those errors are of a different nature, it would be good if could create separate issues for both of them.
@JavituRec

**Comment by konsolas** [comment] 2017-09-02 15:39
Should be fixed next update, but I can't reproduce this myself.

**Comment by konsolas** [comment] 2017-09-04 10:29
According to @craftrise this is still valid.

**Comment by CeIebrimbor** [comment] 2017-09-04 15:42
I had 3 individuals report this right before 3.3.2 was released, and it was broomed because it was "pending fix" with 3.3.2. I think it deserves a "Critical" now. Some servers don't notice it because their server restarts after AAC crashes it and the error is seemingly not consistent, but it is still a nasty bug.

**Comment by Janmm14** [comment] 2017-09-04 17:34
Interesting here is the output of `java -version`, it shows you exact jvm version and vendor.
Currently there is the theory that maybe the openjdk is causing this problem.

**Comment by konsolas** [comment] 2017-09-16 19:24
This was fixed earlier according to @craftrise

**Closed by konsolas** 2017-09-16 19:24 UTC
Labels: critical, error
