### ISSUE TITLE
FightSpeed false positive

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#35] opened 2016-10-19 14:15 UTC
I don't know how you are calculating the fight speed but I get up to 26 cps according to the fightspeed check.
(My real click speed: ~ 12 cps maximum)
Tested with mc 1.10 on the aac3 test server.

**Comment by CeIebrimbor** [comment] 2016-10-19 15:01
There are 2 levels if I'm not mistaken. There is real-time click speed making sure a player isn't hitting at 21+ CPS and consistent click speed making sure a player isn't hitting above 16 for long testing periods. The consistent check has been flawed since it was added and I haven't enabled it in forever. I turn it off for my config clients. Well...when I had clients. That has slowed from 10/week to 3/month. lol

You may have been hit for the consistency check (wouldn't surprise me).

**Comment by Photon-GitHub** [comment] 2016-10-19 15:04
But how could someone hitting maximum 12 cps trigger a 26 cps violation?

**Comment by CeIebrimbor** [comment] 2016-10-19 15:21
This is why I am unable to suggest it was such a detection. I don't have access to the log. That will be the tell. Or a video with the verbose of course.

**Comment by konsolas** [comment] 2016-10-19 18:01
Since I don't think this is major/going anywhere I'm going to close this.

**Comment by Photon-GitHub** [comment] 2016-10-20 17:53
The bug is only appearing if you are spamming left-click (attack) and right-click (interact) simultaneously and kicks you very fast (I can reach 12 cps legit and it detects both the clicking so I get unnatural 24 cps).
Especially on 1.8 this can lead to problems because of block-hitting.

**Comment by CeIebrimbor** [comment] 2016-10-20 18:10
Produce video. If you know the condition, do the ground work to prove its an issue. Konsolas attempted to reproduce already.

**Comment by Photon-GitHub** [comment] 2016-10-20 20:13
Just clicking on an entity, I don't know what I should show...

**Comment by konsolas** [comment] 2016-10-21 19:10
Can I have a screenshot of the message shown?

**Comment by konsolas** [comment] 2016-10-21 19:30
Potential fix for right-clicking on the test server. @Photon-GitHub can you verify?

**Comment by konsolas** [comment] 2016-10-22 13:46
Seems to be fixed on the test server.

**Closed by konsolas** 2016-10-22 13:46 UTC
Labels: bug, planned
