### ISSUE TITLE
Add aac.violations permission

### ISSUE THREAD

**Issue by Fleodas** [konsolas/AAC-Issues#702] opened 2017-06-02 16:07 UTC
It would be useful to allow staff other than admins to see the violations gui, it's actually very useful to check players before they are kicked and to find false positives.

I can't add the aac.admin permission to my whole staff because I don't want my mods to be able to toggle checks and reload AAC.

You could add an new command such as /aacviolations with aac.violations permission wich would open the violations menu.

**Comment by Photon-GitHub** [comment] 2017-06-03 14:18
Duplicate of #368

**Closed by Photon-GitHub** 2017-06-03 14:18 UTC
Labels: feature
