### ISSUE TITLE
[AAC5] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC5

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2120] opened 2021-01-08 13:03 UTC
Error:
https://pastebin.com/raw/qtXpCBB6

### Core information
**Server version**: 1.16.4 (Paper Build 394)

**AAC version**: 5.0.7

**AAC config**: 5.0.7|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 492

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment] 2021-01-08 18:39
Duplicate of #2109

**Closed by konsolas** 2021-01-08 18:39 UTC
Labels: 1. error, 4. duplicate
