### ISSUE TITLE
Jumping With Carpets makes you Glitch

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#1304] opened 2018-03-17 12:46 UTC
Video of the bug: https://www.youtube.com/watch?v=JJw6MT1Ohu4&feature=youtu.be

Version of AAC: The latest 👍

Protocol Lib version: The latest

Details of the video: When you walk with carpets in your area, you can be glitched a lot.

Name of the client: No client, just AAC bug

**Comment by Photon-GitHub** [comment] 2018-03-17 13:07
„Latest“ is not a valid version as those can change quickly, especially with ProtocolLib development builds. Please add your actual AAC and ProtocolLib version. 

Also please test with a vanilla client as mods usually regarded as „legit“ can affect your game in unexpected ways.

**Comment by Minemaniak** [comment] 2018-03-17 13:17
Duplicate of https://github.com/konsolas/AAC-Issues/issues/1221, in the comment in this issue I mentioned, that it happens with all non-full blocks, including carpets

**Comment by konsolas** [comment] 2018-03-20 20:46
Closing due to failure to provide information.

**Closed by konsolas** 2018-03-20 20:46 UTC
Labels: 1. bug, 2. move, 3. insufficient info, 4. inactivity
