### ISSUE TITLE
ClassCastExceptions with Java 8 AAC

### ISSUE THREAD

**Issue by Cryptite** [konsolas/AAC-Issues#586] opened 2017-04-16 13:20 UTC
### Issue description

PlayerMoveEvent Stack Trace: https://hastebin.com/zunovasuzi.vbs
(Nofall?) Stack Trace: https://hastebin.com/ahanahuyev.vbs

### Core information
**Server version**: PaperSpigot git-Paper-1081 (MC: 1.11.2)

**AAC version**: 3.1.5-b2

**ProtocolLib version**: 4.2.1 b354

**Comment by konsolas** [comment] 2017-04-16 15:26
Please leave a comment on this issue if you are also having this problem, with information about your spigot build and plugins.

**Comment by konsolas** [comment] 2017-04-16 16:08
@Cryptite could I have your plugin list?

**Comment by Cryptite** [comment] 2017-04-16 17:29
Plugins (38): CoreProtect, PlayerHeads, dynmap, WorldEdit, Flight, BountifulAPI, Chairs, WorldBorder, Votifier, WorldGuard, EntityDetection, Multiverse-Core, ProtocolLib, LibsDisguises, AAC, BossBarAPI, RateOfXray, PermissionsEx, EffectLib, ParticleLIB, ConditionalCommands, PluginCatcher, Multiverse-NetherPortals, Vault, Prism, MiniaturePets, CombatTagPlus, Essentials, AACAdditionPro, HolographicDisplays, Brewery, Citizens, MythicMobs, VanishNoPacket, EchoPet, Denizen, Depenizen, TheArtifact

TheArtifact is my own plugin, FYI. So you won't find it looking around on spigot or anything.

**Comment by SlimeDog** [comment] 2017-04-16 17:50
Plugins (77): RedstoneProximitySensor, BlueBook, Elevators, AdminVault, PlaceholderAPI, TrashDisposal, Pl3xMOTD, CameraObscura, WorldResourcepacks, FastCraftPlus, LuckyBlock, WhatPlugin, EasyFirework, EntityList, EditableSign, LightAPI, TopLite, WorldEdit, HungerKeeperPlus, CustomShields, InventoryPlus, Skript, CityWorld, Realistic-Swimming, MCLib, DisableItemFrameRotation, MazeCraft, ProtocolLib, VoidGenerator, RedstoneClockDetector, DeluxeMenus, PermissionsEx, SignEditor, RadarJammer, Laser, ItemJoin, Vault, BloodInMinecraft, MassiveCore, PerWorldInventory, WorldGuard, AAC, BiomeFinder, ASkyBlock, SignBoard, AdvancedKitsReloaded, ShinyItems, Orebfuscator4, Essentials, Statscraft, Multiverse-Core, VoidSpawn, Citizens, Shopkeepers, Multiverse-Portals, BlockParticles, StreetlightsAdvanced, Factions, ExtraHardMode, CT-Core, Multiverse-NetherPortals, HeadsPlugin, EasyEnchant, CommandSigns, HeadSweeper, Sentinel, HeadsInventory, MinigamesLib, MGSplegg, MGFlyingCars, MGConquer, MobHunting, MGMobEscape, MGSnake, Thirst, ScoreboardStats

**Comment by konsolas** [comment] 2017-04-16 17:57
One noticable plugin in common is Citizens, which could be the cause if there are enough player NPCs present. @Cryptite @SlimeDog do either of you use player NPCs?

**Comment by SlimeDog** [comment] 2017-04-16 18:18
I use player NPCs. But they don't move.

**Comment by Cryptite** [comment] 2017-04-16 18:30
I use quite plenty, yes. They do move if you have "look" turned on (they turn their heads towards players)

**Comment by konsolas** [comment] 2017-04-16 18:38
What I suspect:
 - Citizens NPCs load first on startup. AAC tries to run a check on them for some reason.
 - AAC registers CraftPlayer#getHandle as CitizensPlayerNPC#getHandle instead, because that's the first Player object it sees
 - AAC tries to call CitizensPlayerNPC#getHandle instead of CraftPlayer#getHandle, after the JVM optimizes the call, resulting in IllegalArgumentException.

**Comment by SlimeDog** [comment] 2017-04-16 18:45
This behavior did not occur through 3.5.1. So something in the handling changed in 3.5.1-b1.

**Comment by konsolas** [comment] 2017-04-16 18:48
I've tested the fix with @Cryptite, and so far it appears that the error has been fixed. 
The fix involves simply checking the Class<? extends Player> passed in, and keeping separate methods for each one to ensure the correct method is called for NPCs and normal CraftPlayers.

**Comment by konsolas** [comment] 2017-04-16 18:55
Fixed in 3.1.5-b3, confirmed by @Cryptite.

**Closed by konsolas** 2017-04-16 18:55 UTC
Labels: error
