### ISSUE TITLE
Ice Jump and Sprint False Positve

### ISSUE THREAD

**Issue by DasCanard** [konsolas/AAC-Issues#1051] opened 2017-10-28 12:53 UTC
### Issue description

Report Video: https://streamable.com/uze25

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: PermissionsEx, WorldEdit, Essentials, EssentialsSpawn, Multiverse-Core, WorldGuard, ProtocolLib, AAC, AACAdditionPro, MineResetLite

### Special environment information
**ViaVersion version**: N/A (or N/A)

**ProtocolSupport version**: N/A (or N/A)

**ViaBackwards version**: N/A (or N/A)

**BungeeCord plugins**: N/A (or N/A)

### Configuration
Standard

**Comment by Janmm14** [comment] 2017-10-28 12:57
Looks like a dupe of #933

**Closed** 2017-10-28 12:59 UTC
Labels: 1. bug, 2. move, 4. duplicate
