### ISSUE TITLE
[Improvement] Disallow breaking blocks while attacking with killaura

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#17] opened 2016-10-16 16:49 UTC
Hack clients can do both parallel.

**Comment by Photon-GitHub** [comment] 2016-10-16 16:50
They can not start the block breaking while not looking at the block but they can end it - pretty much a duplicate of the BlockBreaker issue...

**Comment by Janmm14** [comment] 2016-10-16 17:23
Possibly, however this aims to stop hack clients to do other things while breaking a block. This is a difference.

**Comment by konsolas** [comment] 2016-10-17 17:34
This sounds like a relatively unimportant feature, in view of other interaction features that have been requested. It's not worth its own check.

**Closed by konsolas** 2016-10-17 17:34 UTC
Labels: feature
