### ISSUE TITLE
Aackick and conditional command error when trying to kick a player offline

### ISSUE THREAD

**Issue by xion87** [konsolas/AAC-Issues#281] opened 2016-12-26 09:28 UTC
I just see this, by using latest release
https://hastebin.com/zeqalenatu.vbs

**Comment by geNAZt** [comment] 2016-12-26 09:36
Related to https://github.com/konsolas/AAC-Issues/issues/267

**Comment by konsolas** [comment] 2016-12-26 10:07
Closing as a duplicate of #267

**Closed by konsolas** 2016-12-26 10:07 UTC
Labels: duplicate
