### ISSUE TITLE
fix your servers

### ISSUE THREAD

**Issue by swepyh** [konsolas/AAC-Issues#1992] opened 2020-08-20 04:18 UTC
[AAC] Hooked into PlaceholderAPI
[21:17:04 ERROR]: [AAC] Invalid server response
[21:17:04 INFO]: [AAC] Disabling AAC v4.4.0

idek whats happening, just started to happen when i started my server
Server version: PaperSpigot 1.16.1

**Comment by Janmm14** [comment] 2020-08-20 08:35
Duplicate of #1991

**Closed by Janmm14** 2020-08-20 08:35 UTC
