### ISSUE TITLE
False Positive | Move false positive

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#1269] opened 2018-03-04 16:18 UTC
Tested in test.kons.co. 
Client version: 1.8.9

AAC version:
http://prntscr.com/impts1

False positive: https://gyazo.com/097c1d633a019d00697b8237631bd812

**Comment by Minemaniak** [comment] 2018-03-04 16:45
Duplicate of https://github.com/konsolas/AAC-Issues/issues/1231

**Comment by Janmm14** [comment] 2018-03-05 01:10
Duplicate of #1231

**Closed by Janmm14** 2018-03-05 01:10 UTC
