### ISSUE TITLE
Timer false positives.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2119] opened 2021-01-07 23:49 UTC
For reference the **speed** and **fly** mentioned in this report pertains to the Essentials /speed and /fly commands.
Users who fly at full speed, upon immediately halting their flight, get kicked for Global/Timer depending on their actions.

We have received several complaints that this is making the game unplayable, with some being unrelated to speed/flight itself.
Below is our most recent report that includes a video, time stamps and logs.
Hopefully this helps track the issue down.

Original user report:
https://ecocitycraft.com/forum/threads/anti-cheat-report-kicked-by-anticheat-501.207837/

Video evidence: https://youtu.be/sh9gPz0FySo
Logs from kicks (501 [Global]) & (511 [Timer]): https://pastebin.com/raw/bjUZzybV

PS: Several users report that a "bad internet connection" on their end amplifies these problems.

### Core information
**Server version**: 1.16.4 (Paper Build 393)

**AAC version**: 5.0.6

**AAC config**: 5.0.6|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 492

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by ChiboYen** [comment] 2021-01-08 00:09
Thanks for this report, it appears similar to #2116 and #2115

**Comment by konsolas** [comment] 2021-01-08 20:34
Duplicate of #2115

**Closed by konsolas** 2021-01-08 20:34 UTC
Labels: 1. bug, 2. move, 4. duplicate
