### ISSUE TITLE
Bypassing on test server killaura and hitbox false positives

### ISSUE THREAD

**Issue by LinsaFTW** [konsolas/AAC-Issues#915] opened 2017-08-31 01:10 UTC
On the test server i can use killaura from jigsaw and it doesnt detect me even with max reach and 8cps...

~~And sometimes it detects me because of hitbox when im not using anything. only mod i was using is optifine. Version 1.8.8~~

~~I made some testing on my own test server , and while watching the verbose i noticed normal players can reach up to 3.80 blocks reach.~~

If you want any videos bypassing and testing theres no problem i can make some...

**Comment by ItzSomebody** [comment] 2017-08-31 05:32
I think players can reach up to 4.5 blocks to compensate for lag.

As for Jigsaw, can we see your config?

**Comment by LinsaFTW** [comment] 2017-08-31 06:13
Jigsaw Reach max and cps on 6

**Comment by LinsaFTW** [comment] 2017-08-31 06:15
Cps on 5 is a good value too , it detects it as hitbox after a lot of time.

**Comment by LinsaFTW** [comment] 2017-08-31 08:55
I think this can be fixed by adding a option in config called vl-clear-time or something like that that removes the violations after a selected amount of ticks because it detects it but it instantly clears it , comprobed by doing some testing on my server with verbose on

**Comment by CeIebrimbor** [comment] 2017-08-31 14:16
> On the test server i can use killaura from jigsaw and it doesnt detect me even with max reach and 8cps...

Can you get video of what you believe is a significant advantage in pvp. That's all we need if it was on the test server.

> And sometimes it detects me because of hitbox when im not using anything. only mod i was using is optifine. Version 1.8.8

This is known. It's pending fix in another issue.


> I made some testing on my own test server , and while watching the verbose i noticed normal players can reach up to 3.80 blocks reach.

This is known. Hitbox will detect anything above 3.8 and Killaura <4.5. Anything in the 3.5-3.7 range will rely on extended combat and detection by Heuristics (until Hitbox is tinkered with).

I am going to mark as "Insufficient Info" just pending your addition of a video. All other comments will be scratched. We will just focus on your supposed bypasses in this issue.

**Comment by CeIebrimbor** [comment] 2017-08-31 14:18
> I think this can be fixed by adding a option in config called vl-clear-time or something like that that removes the violations after a selected amount of ticks because it detects it but it instantly clears it , comprobed by doing some testing on my server with verbose on

Hitbox gains VL with each illegal hit and only reduces VL with a legal hit. So if a client only hits illegally, the VL will never go down.

**Comment by LinsaFTW** [comment] 2017-08-31 19:58
The killaura doesnt work too good and nothing detects it but it looks like im hitting from 4 blocks for the other players.

Well , they hit more than 14 5.0 reach hits when starting pvp as they do jitter click , so..

**Comment by CeIebrimbor** [comment] 2017-08-31 20:10
So it's a TP KillAura? (teleport) Or maybe a ghost client.

**Comment by LinsaFTW** [comment] 2017-08-31 20:23
Players doesnt have any hacks i did ss to them before testing and they just got detected by hitbox a lot of time , sometimes in the verbose it shows they hit 5.0 blocks i think its because of the ping because they have like 200ms - 300ms

**Comment by LinsaFTW** [comment] 2017-08-31 20:24
But this should be fixed... :/ and it detects a lot of fly when the players get hit with a fishing rod

**Comment by ItzSomebody** [comment] 2017-08-31 22:51
Just add conditionalcommand if it's just an issue of ping

**Comment by LinsaFTW** [comment] 2017-09-02 06:57
They have like 100 - 200 ping but lag spikes so i cant do anything and hackers can use ping spoof :(

**Comment by konsolas** [comment] 2017-09-02 15:55
This seems to be a duplicate of #873

**Closed by konsolas** 2017-09-02 15:55 UTC
Labels: duplicate, insufficient info, ¯\_(ツ)_/¯
