### ISSUE TITLE
NullPointerException & Updater always tells new version ist available

### ISSUE THREAD

**Issue by Sprax2013** [konsolas/AAC-Issues#1059] opened 2017-10-31 13:34 UTC
### Core information
**Server version**: Screenshot

**AAC version**: 3.3.4

**ProtocolLib version**: 4.3.0

**Plugin list**: Screenshot

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

![bildschirmfoto am 2017-10-31 um 14 30 23-fullpage](https://user-images.githubusercontent.com/7331598/32226315-8c8b755a-be48-11e7-98e5-c6ec359b5450.png)

**Comment by Janmm14** [comment] 2017-10-31 13:44
Duplicate of #1028

**Closed by Janmm14** 2017-10-31 13:44 UTC
