### ISSUE TITLE
ViaVersion 4.0 dev build incompatible

### ISSUE THREAD

**Issue by KolakZ** [konsolas/AAC-Issues#2259] opened 2021-05-11 15:18 UTC
It would be great to see AAC update to the ViaVersion protocol of the latest dev builds because mcMMO only works with the dev builds so I am forced to use it but AAC doesn't work with it.

**Comment by Janmm14** [comment] 2021-05-19 08:33
Duplicate of #2255

**Closed by Janmm14** 2021-05-19 08:33 UTC
Labels: 1. bug, 3. compatibility, 3. multiversion
