### ISSUE TITLE
AAC blocking player respawn movements?

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#986] opened 2017-09-28 21:53 UTC
Video: https://www.youtube.com/watch?v=ou-VvcL0ZU0&feature=youtu.be
AAC-Log: https://pastebin.com/22BBVm3G
Server-Log: https://pastebin.com/EP9UYdjr

**Comment by CeIebrimbor** [comment] 2017-09-28 22:31
Video "unavailable"

**Comment by Hyronymos** [comment] 2017-09-28 22:34
ups, done

**Comment by CeIebrimbor** [comment] 2017-10-04 18:35
Is this something that happens frequently or was this a freak instance? Possibly a teleport desync? What is your `tp_accept_threshold` setting in "move"?

**Comment by CeIebrimbor** [comment] 2017-10-05 16:19
Labeling Insufficient for now.

**Comment by Hyronymos** [comment] 2017-10-08 14:30
tp_accept_threshold: 0.001 still happened with tp_accept_threshold: 0.08

**Comment by Janmm14** [comment] 2017-10-08 14:35
Best possibility for debugging in that case is `/aacdebug playername` - it will genrate a file showing why AAC thinks it has to block all movements of a player because he did not arrived at his respawn/teleport location yet.

**Comment by Hyronymos** [comment] 2017-10-10 20:04
I will try it

**Comment by Janmm14** [comment] 2017-10-10 20:48
Similar issues are being looked at currently.

**Comment by Janmm14** [comment] 2017-10-12 22:28
Possibly a duplicate of #1001.
In case this issue is not fixed by AAC 3.3.4, please request a reopen.

**Closed by Janmm14** 2017-10-12 22:28 UTC
Labels: insufficient info

**Comment by Janmm14** [comment] 2017-10-19 01:32
Discussion can go on at issue 1035.
