### ISSUE TITLE
Errors spam/ Players can't open the chests

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1105] opened 2017-12-08 09:35 UTC
Huge errors spam.
Players can not open the chests.

### Core information
**Server version**: paper 1.8.8
**AAC version**: latest
**ProtocolLib version**: lastStableBuild
**ViaVersion version**: latest

Log: https://pastebin.com/WeqreTbG
Video: https://yadi.sk/i/PldK-Kfu3QRodJ

**Comment by CeIebrimbor** [comment] 2017-12-08 15:17
Why did you put "latest" for ProtocolLib when you use the version from June? 🤔 

Go ahead and swap to the _actual_ latest and report back.
http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by Hyronymos** [comment] 2017-12-08 18:52
Same problem with ProtocolLib 4.2.0. It does happens every week only 1x

#1100

**Comment by CeIebrimbor** [comment] 2017-12-08 20:30
Duplicate of #1100

**Closed by CeIebrimbor** 2017-12-08 20:30 UTC
