### ISSUE TITLE
Fly False Positives when Sleeping in Bed

### ISSUE THREAD

**Issue by SioWolf** [konsolas/AAC-Issues#334] opened 2017-01-02 17:33 UTC
### Description

When players sleep in a bed it triggers the flight check. This bug affects every player on my server. I was standing in-game watching another player sleep and while they were laying in the bed I received notifications of possible flight hacks, followed by the server kicking them.

I am using Celebrimbor's Fly settings which do nothing but add lenience.

Video from player's perspective: https://youtu.be/KuCSEU-6TFQ
LOG: http://pastebin.com/BE1EyiNu

### Core information
**Server version**: git-Paper-1011 (MC: 1.11.2)

**AAC version**: 3.0.1

**ProtocolLib version**: 4.2.0

**Plugin list**: http://pastebin.com/PV2H6GCw

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment] 2017-01-02 17:58
tolerance: 0.07
For reference

**Comment by Rqcco** [comment] 2017-01-02 21:21
Duplicate of #246

**Closed** 2017-01-02 21:21 UTC
Labels: bug, duplicate, move

**Comment by Janmm14** [comment] 2017-01-03 09:55
@SioWolf For 1.11 use ProtocolLib 4.2.1
