### ISSUE TITLE
Failed to pull entity hitboxes from NMS

### ISSUE THREAD

**Issue by LoXR** [konsolas/AAC-Issues#2148] opened 2021-01-31 05:03 UTC
**Issue description**
Everytime i've used AAC on my hubs, it always spams the hitbox error.

**Error**
https://mcpaste.io/814747c8b3f10b34

### Core information
**Server version**: 
Paper 1.13.2

**AAC version**: 
5.0.10

**ProtocolLib version**: 
ProtocolLib version 4.6.0-SNAPSHOT-b66

### Special environment information
**ViaVersion version**: ??
ViaVersion version 3.2.1-SNAPSHOT

**ProtocolSupport version**: ??
N/A

**ViaBackwards version**: ??
ViaBackwards version 3.2.1-SNAPSHOT

**BungeeCord plugins**: ??
AuthMeBungee, BconfReloader, BungeeMSG, BungeeStaff, EnhancedBungeeList, FastLoginBungee, Floodgate-bungee, HubMagic, nuvotifier, PixelMOTD, Skinsrestorer, UltimateFriends

**Comment by LoXR** [comment] 2021-02-16 10:10
Will report that is still doesnt work on latest version: https://mcpaste.io/60a45ad6648b8a2e
Server Version: 1.13.2
Client version: 1.12.2 (used a hacked client to test aac, sadly saw that spamming console still)

**Comment by konsolas** [comment] 2021-03-04 16:02
Duplicate of #2140

**Closed by konsolas** 2021-03-04 16:02 UTC
Labels: 1. error, 3. not fixed
