### ISSUE TITLE
Problem with Player velocity

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#2184] opened 2021-02-23 01:16 UTC
Same as https://github.com/konsolas/AAC-Issues/issues/2131 , AAC is canceling vaild velocity movements example from JumpPads plugin or from slime blocks.

### Core information
**Server version**: 1.8.8

**AAC version**: 5.0.1.1

**ProtocolLib version**: 4.6.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: 3.2.1

**ProtocolSupport version**: ??

**ViaBackwards version**: 3.2.1

**BungeeCord plugins**: -

### Configuration

default

**Comment by Janmm14** [comment] 2021-02-23 10:18
Provide AAC debug please

**Comment by Xayanix** [comment] 2021-02-23 11:29
https://prnt.sc/104qgte

**Comment by konsolas** [comment] 2021-02-23 11:31
![image](https://user-images.githubusercontent.com/9408210/108837764-a5c61d80-75ca-11eb-9df0-614f01caacf8.png)

Try to only set velocity once

**Comment by Xayanix** [comment] 2021-02-23 12:06
Ok, i will check it soon. But there is a problem also with vanilla slime blocks. If you jump down and place slime block below then you should be knocked up, but AAC very often cancels velocity.

**Comment by Xayanix** [comment] 2021-02-24 00:23
https://www.youtube.com/watch?v=ChW4geswRiE
0:07 player should be knocked up but got stuck
0:12 invaild setbacks

I was playing on pure 1.8.8 Minecraft on 1.8.8 server. I didnt have any macros etc.

**Comment by Xayanix** [comment] 2021-02-24 00:41
+ slime blocks very often deal dmg.

**Comment by Janmm14** [comment] 2021-02-24 01:47
Just making sure that you know that sneaking makes slime blocks deal fall damage (and not throwing player up again)

**Comment by Xayanix** [comment] 2021-02-24 11:36
Sure but as you could see in the chat AAC set me back.

**Comment by konsolas** [comment] 2021-02-25 10:37
Duplicate of #1911

**Closed by konsolas** 2021-02-25 10:37 UTC
Labels: 1. bug, 2. move, 3. waiting for reply

**Comment by Xayanix** [comment] 2021-02-27 01:07
So when it will be fixed? This is game breaking issue.
