### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Heliosard** [konsolas/AAC-Issues#1500] opened 2018-09-09 13:38 UTC
### Issue description
Hi,
A recurring error is present in the console.
Console error: https://gist.github.com/Heliosard/d4013044c227e412e9492b132d5010c7

### Core information
**Server version**: git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.5.0

**ProtocolLib version**: ProtocolLib v4.4.0-SNAPSHOT-b400

### Special environment information
**ViaVersion version**: 1.5.0

**Comment by Janmm14** [comment] 2018-09-09 14:26
Duplicate of #1481

**Closed by Janmm14** 2018-09-09 14:26 UTC
Labels: 1. error, 2. move, 4. duplicate
