### ISSUE TITLE
Move false positive check on slimeblock piston

### ISSUE THREAD

**Issue by blek-id** [konsolas/AAC-Issues#1785] opened 2019-09-23 07:36 UTC
### Issue description
Log: https://pastebin.com/T7Bjd3iX
Player would be kicked when using machine I posted on the attachment.
![2019-09-23_14 31 19](https://user-images.githubusercontent.com/26654664/65408466-83493700-de0f-11e9-9a3c-066f347ed0c6.png)

### Core information
**Server version**: 1.13.2

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

**Plugin list**: -

### Special environment information
**ViaVersion version**: 2.1.3

**ProtocolSupport version**: -

**ViaBackwards version**: -

**BungeeCord plugins**: -

### Configuration
Using Latest Config from Celebrimbor
v4.2.1 | Ghost | 1

**Comment by konsolas** [comment] 2019-10-03 16:35
Duplicate of #1702

**Closed by konsolas** 2019-10-03 16:35 UTC
