### ISSUE TITLE
False positives of heuristics (pattern P/92)

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1318] opened 2018-03-21 11:26 UTC
### Issue description
The player just ran ...

Log: https://pastebin.com/hzV70nhL
Video  from ReplayMode: https://vk.com/videos308819433?section=uploaded&z=video308819433_456239023/pl_308819433_-1

### Core information
**Server version**: 1.12.2 paper

**AAC version**: 3.3.12

**ProtocolLib version**: v4.4.0-SNAPSHOT

**Plugin list**: AAC, ProtocolLib, ProtocolSupport, Custom

### Configuration
Cel-r
https://pastebin.com/53KteT9x

**Comment by Rerd** [comment] 2018-03-21 12:03
Duplicate of issue #1310.

**Closed** 2018-03-21 12:07 UTC
