### ISSUE TITLE
Killaura semi-transparent entities

### ISSUE THREAD

**Issue by higgs01** [konsolas/AAC-Issues#1271] opened 2018-03-05 21:16 UTC
### Issue description
The killaura check seems to cause following weird issue:

1. Around every player there are flying some semi-transparent entities
2. Each player seems to have multiple semi-transparent clones of himself at the same position

This could be related to #1265 

## Images
1. ![](https://user-images.githubusercontent.com/6546697/36999835-a4c72aa2-20c1-11e8-9bc0-3831e41ab19c.png)
2. ![image](https://user-images.githubusercontent.com/6546697/36999861-c32f4696-20c1-11e8-962c-a079f634bff8.png)

[AAC Debug log](https://hastebin.com/puxiwuxino.rb)
### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.11

**ProtocolLib version**: 4.3.0

**Plugin list**:
- AntiWDL
- FastAsyncWorldEdit
- ImageOnMap
- ArorStandGui
- PlugMan
- HeadDatabase
- CreativeItemControl
- WorldEdit
- PlotSquared
- WorldGuard
- custom plugins...

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
The config is still default.

**Comment by Janmm14** [comment] 2018-03-05 21:31
Duplicate of #1239

**Closed by Janmm14** 2018-03-05 21:31 UTC
