### ISSUE TITLE
Issue that prevents Vanilla Based Teleporting 

### ISSUE THREAD

**Issue by Jet315** [konsolas/AAC-Issues#1085] opened 2017-11-21 18:55 UTC
### Issue description
Prevents users from teleporting using the vanilla /Minecraft:teleport command
Video: https://www.youtube.com/watch?v=eXQKtAkJiTA&feature=youtu.be
I have a command block that executes /minecraft:teleport @p cords - This is blocked by AAC and no log is given.

<This issue still occurs using only AAC, ProtocolLib and Vault installed, so the below I do not really see necessary> - Easily replicable by typing /minecraft:teleport MCName 0 0 0

### Core information
**Server version**: Paper Spigot 1.12.2-R0.1-SNAPSHOT

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: Build number: 173 

**ViaBackwards version**:  N/A

**BungeeCord plugins**: N/A

### Configuration
Ghost config from Celebrimbor

**Comment by CeIebrimbor** [comment] 2017-11-21 19:28
I have not personally experienced this with vanilla teleports, but the same situation has occurred on multiple plugin teleports. No verbose output.

**Comment by CeIebrimbor** [comment] 2017-11-27 05:05
Just found out that this will despawn animal farms. I think it might be tied to Paper 1.12, but doesn't happen w/o AAC.

1. Make small animal pen w/ 4+ animals (I reproduced with cows)
2. Feed/breed the animals
3. Unload chunks
4. Command block teleport a few thousand blocks away to random, unloaded chunks.
5. Return to animal pen
6. No more animals...

**Comment by konsolas** [comment] 2017-12-02 15:00
I've tried the circumstances given in the original issue, but I'm not blocked.

**Comment by CeIebrimbor** [comment] 2017-12-02 15:15
What about the animal despawn @konsolas

Also, I do not get blocked either.

**Comment by konsolas** [comment] 2017-12-03 10:42
That seems to be a different issue entirely

**Comment by konsolas** [comment] 2017-12-03 19:24
I'm going to close this issue because the animal despawn issue isn't teleport blocking.

**Closed by konsolas** 2017-12-03 19:24 UTC
Labels: 1. bug, 2. move, 4. invalid

**Comment by LogGits** [comment] 2017-12-20 17:19
Getting a similar issue with the tp/warp/home commands in essentials with AAC. Was there ever a fix to this?
