### ISSUE TITLE
Motion nofall and LiquidBounce aac 1.9.10 nofall works with no damage... 

### ISSUE THREAD

**Issue by tigrecode** [konsolas/AAC-Issues#1282] opened 2018-03-08 06:18 UTC
So, motion nofall and LiquidBounce aac 1.9.10 nofall works. Please fix this.. 

**Server version**: 1.8.x

**AAC version**: 3.3.11

**ProtocolLib version**: forgot but latest

**Plugin list**: aac, protocollib

**Comment by Slimerblue22** [comment] 2018-03-09 21:04
I've tried all versions of LB nofall and only 1 works **buggy as heck but works** and it seems to only reduce fall damage

**Comment by tigrecode** [comment] 2018-03-10 08:26
No, aac 3_3_11 nofall works with no damage and aac 1.9.10 too

**Comment by konsolas** [comment] 2018-03-10 17:01
Duplicate of #1267

**Closed by konsolas** 2018-03-10 17:01 UTC
Labels: 1. bypass, 2. move
