### ISSUE TITLE
Error | Add locations of different worlds

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1423] opened 2018-07-23 15:53 UTC
### Issue description

Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: insert paper spigot 1.12.2

**AAC version**: insert 3.3.4

**ProtocolLib version**: insert 4.3.0

**Plugin list**: insert

### Special environment information
**ViaVersion version**: insert (or N/A)  1.4.1

**ProtocolSupport version**: insert (or N/A) no

**ViaBackwards version**: insert (or N/A) viabackwards-all-2.3.2-DEV

**BungeeCord plugins**: insert (or N/A) via version

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 
```
 ERROR Could not pass event PlayerInteractEvent to AAC v3.4.0
23.07 17:44:01 [Server] INFO org.bukkit.event.EventException: null
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:460) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
23.07 17:44:01 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151] 23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
23.07 17:44:01 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
23.07 17:44:01 [Server] INFO at org.bukkit.Location.subtract(Location.java:373) ~[Paper-1488.jar:git-Paper-1488]
23.07 17:44:01 [Server] INFO at me.konsolas.aac.I.a(I.java:97) ~[?:?] 23.07 17:44:01 [Server] INFO at me.konsolas.aac.I.a(I.java:108) ~[?:?]
23.07 17:44:01 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor413.execute(Unknown Source) ~[?:?]
23.07 17:44:01 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper-1488.jar:git-Paper-1488]
```

**Comment by CeIebrimbor** [comment] 2018-07-23 16:39
You list that you use AAC 3.3.4, but the console suggests 3.4.0. Please update your ProtocolLib to 4.4.0.

**Comment by leoncp9** [comment] 2018-07-23 16:55
can i use this version? Compilazione #406 (22-lug-2018 0.49.49) ?

**Comment by Janmm14** [comment] 2018-07-24 17:38
The error is unrelated to protocollib

**Comment by Photon-GitHub** [comment] 2018-08-01 17:06
Duplicate of #1422

**Closed by Photon-GitHub** 2018-08-01 17:06 UTC
Labels: 1. error
