### ISSUE TITLE
Task #611 generated an exception

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1377] opened 2018-05-13 15:17 UTC
### Issue description

Console throwing this quite a lot:
https://pastebin.com/raw/rM4PTrdG

Happens randomly, but when it does, it does so several times in a row as seen above.
That is also all the error shows, kinda weird as usually errors show much more information.

EDIT: As per below reply, here's more information:
https://pastebin.com/raw/XH8Sisy0

### Core information
**Server version**: 1.12.2 - Spigot Build 1634

**AAC version**: 3.3.14
**AAC config**: 3.3.14|2-Default-Celebrimbor

**AACAdditionPro version**: 3.11.1
**AACAdditionPro config**: 3.11.1|2-Default-Celebrimbor

**ProtocolLib version**: 4.3.0 Build 390

**Plugin list**: (on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment] 2018-05-13 15:43
Please look throuh your log files, the first exceptions after server start will be longer.
What you see here is java removing stack traces for often thrown exceptions for optimization.

If you do not like that behaviour you can disable it by adding `-XX:-OmitStackTraceInFastThrow` somewhere before `-jar` in your startup command.

**Comment by andrewkm** [comment] 2018-05-13 16:12
@Janmm14 Ah, I did not know that.
Here's some bigger ones :)

https://pastebin.com/raw/8ghN4gsx

**Comment by Janmm14** [comment] 2018-05-13 18:08
Ok so thisseems to be a duplicate of #1357

**Closed by Janmm14** 2018-05-13 18:08 UTC
Labels: 1. error
