### ISSUE TITLE
High wall jump for unlimited time

### ISSUE THREAD

**Issue by MinecraftiUndCo** [konsolas/AAC-Issues#807] opened 2017-07-07 20:07 UTC
### Issue description

A player can jump up a wall multiple times like there is a block under him and his jump height is increased. You see the bypass in the videos below.

* You can see detection output and bug in video
* https://youtu.be/kiAMRxDWUiI
* https://youtu.be/RaEBLhFgqHc
* JigSaw 1.8x0.25, Airjump

### Core information
**Server version**: 1.8.9
**AAC version**: 3.2.1-b1 (newest version)
**ProtocolLib version**: V.4.3.0
**Plugin list**: AAC, AACAdditionPro, ProtocolLib

### Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by CeIebrimbor** [comment] 2017-07-08 01:36
Linked to #748

**Comment by konsolas** [comment] 2017-07-16 17:49
Currently cannot reproduce this issue. Youtube video does not contain AAC verbose format so there is not enough information about the issue to determine a solution. It is unclear if the player has any jump modifying effects.

**Comment by konsolas** [comment] 2017-07-16 18:05
Going to close this as a probable duplicate of #815 which is getting fixed anyway.

**Closed by konsolas** 2017-07-16 18:05 UTC
Labels: bypass, duplicate, insufficient info
