### ISSUE TITLE
Killaura check needs to be re-worked. (not heuristics)

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#581] opened 2017-04-15 19:27 UTC
Video: https://www.youtube.com/watch?v=sMri9_pbESw&feature=youtu.be

Summary:
I think that instead of using the current method of detecting killaura (spawning mobs and animals inside players), we should only be spawning players inside players. Spawning them strategically inside players to pickup certain killaura types and pickup killauras that attack all entities(including invisibles). I show in the video how AAC spawns entities, and how GCHEAT spawns entities. GCHEAT only spawns players and no mobs where as AAC doesn't spawn any players, yet spawns mobs. Because GCHEAT is only spawning players, it doesn't effect hit detection at all but AAC spawning mobs inside players really effects the hit detection a lot. I have my min_dist set so high because of the hit detection issue. Instead of trying to make the hit detection better with the current detection of killaura, i think you should just pick up the way GCHEAT is doing it. In doing so, you could get rid of a lot of variables in the config. GCHEAT doesnt have a combat tag feature built in so they just spawn the entities if you are in a duel but AAC would utilize its combat tag feature and only spawn entities if you are in combat. But it would most likely have to spawn entities on everyone around you up to a certain distance, to make the check accurate. As well, if the entities are client side, people with high ms wouldn't be false-banned. The entities would wait on the player model that the server sends the client, then add the entities in, and update them.

**Comment by konsolas** [comment] 2017-04-16 10:57
the hit detection problem here is not so much the hitboxes of the mobs - I only picked EntityTypes which had identical internal hitboxes to the player (0.6/1.8). It's more of the offset at which they are placed.

The problem is, if the mob hitboxes are placed too close to the player, latency makes the one which the player hits more up to chance. 

Will experiment with placing the mob hitboxes closer to the player.

**Comment by SnakeDaoust1232** [comment] 2017-04-16 14:49
Hmmmm.

**Comment by SnakeDaoust1232** [comment] 2017-04-16 16:25
I just did my own little test. And as expected. With these settings: https://hastebin.com/qozomuzuse.makefile Hit detection is terrible. I did a fight with my staff and i would like to say we had 50% hit loss. Literally. What i mean by that is. When looking and clicking on the player, it should have allowed two hits, but only one registered.

**Comment by konsolas** [comment] 2017-04-16 19:06
@SnakeDaoust1232 try increasing max_diff to 10 to check that it's the NPCs that are affecting the hit detection.

**Comment by SnakeDaoust1232** [comment] 2017-04-16 23:01
@konsolas So i tried these settings. https://hastebin.com/qaloquyato.makefile And the im pretty sure all the hits are registering now. But the kb and reach feel weird. I originally tried 3.8 reach since im pretty sure thats default. 3.6 feels way better than 3.8 but it all stills feels weird and choppy. But for sure the hits are registering now.

**Comment by Janmm14** [comment] 2017-04-17 01:30
> Ever since you removed the feature that allowed us to change how far away from the player do we want to spawn the NPC's.

That option was for the old forcefield entity, the killaura check behaves differently.

**Comment by SnakeDaoust1232** [comment] 2017-04-17 01:59
I know but why do we need a reach variable if the invisible entities are spawned in the player. I can understand why if we were using the old Forcefield check, but the new one... I don't see a point for it.

**Comment by SnakeDaoust1232** [comment] 2017-04-22 03:24
@konsolas I've gotten around 10 false bans so far. With my min dist set around 5.0. All people with high ms. Im positive it's related to this issue, https://github.com/konsolas/AAC-Issues/issues/564. And maybe the reach issue I posted. The reach check is 1 block off I believe.

**Comment by SnakeDaoust1232** [comment] 2017-04-22 03:25
Any insight as to you working on the KA check?

**Comment by konsolas** [comment] 2017-04-29 10:50
After 3.1.6, combat is likely to get some more updates.

**Comment by jonesdj1** [comment] 2017-05-01 13:35
gcheats invis players are a trick to detect people who hit the real entity instead of the invis ones

**Comment by Janmm14** [comment] 2017-05-02 00:09
that technique is known

**Comment by SnakeDaoust1232** [comment] 2017-05-17 21:18
This and https://github.com/konsolas/AAC-Issues/issues/564 really need to be looked into. I'm getting many players getting false banned.. which should be impossible since these are my killaura settings: https://hastebin.com/judeserewu.bash

**Comment by jQuery0** [comment] 2017-07-07 09:09
so when is combat getting updates??

**Comment by Janmm14** [comment] 2017-08-23 18:31
@jQuery0 combat is getting updates, but the check named "killaura" might not always get updates.

Additionally I do not see any misconecption of the check and I wonder how the check can have so many false positives.

**Comment by Rerd** [comment] 2017-10-04 19:47
I say we make it so invisible players are spawned, like snake said as gcheat does, then we add another permanently invisible player maybe behind the player that is attacking the opponent about 1-2 blocks away. This will check if someone is bypassing Normal by hitting invisible entities (which bypasses currently) so if they do, they will also hit the invisible entity behind them which will then flag for Normal.

**Comment by ItzSomebody** [comment] 2017-10-04 21:11
@SnakeDaoust1232 not sure if you know this, but it is one of the general principles good programs would go against having the entity spawned constantly. By despawning the entities it might also save some server resources.

@Rerd @SnakeDaoust1232  fyi, GCheat also spawns entities in players.

Imo, both are good suggestions, I still wish the old AAC Forcefield check was still implemented. But there is @Photon-GitHub's AACAdditionPro which has its own NPC check which has an API that lets you do basically anything with it.

**Comment by Janmm14** [comment] 2017-10-04 21:39
AAC will not readd an invisible player behind the player.

**Comment by CeIebrimbor** [comment] 2017-10-14 01:40
From what I was told, SnakeDaoust1232 is no longer running a server (maybe a rumor?). Will close this since it is technically categorized as a Feature request. AAC dev can re-open if he thinks it is a future implementation.

**Closed by CeIebrimbor** 2017-10-14 01:40 UTC
Labels: 1. feature, 2. combat
