### ISSUE TITLE
Again a water bug

### ISSUE THREAD

**Issue by Camirlot** [konsolas/AAC-Issues#406] opened 2017-01-28 21:35 UTC
### Issue description

Actually there's a bug with water.
https://www.youtube.com/watch?v=QtbQcPCFtu0&feature=youtu.be
https://www.youtube.com/watch?v=2RHOod8efzQ&feature=youtu.be

### Core information
**Server version**: 1.8.8

**AAC version**: 3.0.2b1

**ProtocolLib version**: 4.20

**Plugin list**: -

### Special environment information

_not needed_

**Comment by geNAZt** [comment] 2017-01-28 21:37
Duplicate of https://github.com/konsolas/AAC-Issues/issues/395

**Comment by Camirlot** [comment] 2017-01-28 21:53
Don't thought that it's the same. Sorry :)

**Comment by geNAZt** [comment] 2017-01-28 21:55
Water is quite buggy currently. If you jump in from a side it can bug you in your first video. If you jump in from the top it can happen as in my issue or in your second video

**Closed** 2017-01-28 22:25 UTC
Labels: bug, critical, move
