### ISSUE TITLE
false positive when switch bow or food 

### ISSUE THREAD

**Issue by visionfutur** [konsolas/AAC-Issues#1859] opened 2020-01-07 04:48 UTC
AAC; 4.3.4
video: https://streamable.com/zbk1w
the previous issue you said i enable sprint. but in this video i didn't enable sprint.

**Comment by Janmm14** [comment] 2020-01-07 06:54
Why you don't just make a video without a cheat client?

**Comment by visionfutur** [comment] 2020-01-07 07:19
I recorded it 1 week ago. So... 
if you want i can record again

**Comment by konsolas** [comment] 2020-01-07 16:42
Duplicate of https://github.com/konsolas/AAC-Issues/issues/1722

This issue can't be fixed for 1.8 clients.

**Closed by konsolas** 2020-01-07 16:42 UTC
Labels: 4. duplicate
