### ISSUE TITLE
[CRITICAL] AAC Startup Error - Server does not start [3.5.0]

### ISSUE THREAD

**Issue by yyunusyigit** [konsolas/AAC-Issues#1497] opened 2018-08-30 08:32 UTC
- The problem is not always, it happens randomly.
- Spigot version: 1.8.8, AAC version: 3.5.0, ProtocolLib: 4.3.0

Startup error:
https://hasteb.in/xitahali.css

Other startup error:
https://hasteb.in/exucuyug.md

Again, other startup error:
https://hasteb.in/dekigepu.md

My opinion: Its fully obfuscator issue.

**Comment by Minemaniak** [comment] 2018-08-30 08:47
1. Spigot 1.8.9 doesn't exists. What is your real spigot version?
2. What is java version on the server? Please paste output of java -version

**Comment by yyunusyigit** [comment] 2018-08-30 08:52
@Minemaniak , yes version 1.8.8.

openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

**Comment by Minemaniak** [comment] 2018-08-30 09:58
This Java version is over 7 months old. Try updating to latest java version and check if issue still persists.

**Comment by yyunusyigit** [comment] 2018-08-30 10:05
@Minemaniak , this is not java issue. Only AAC issue.

**Comment by Minemaniak** [comment] 2018-08-30 11:13
Yes, but it may be caused by old java version which doesn't work well with AAC.

**Comment by Janmm14** [comment] 2018-08-30 21:34
I don't think thats relevant here. AAC's startup doesn't do much with ProtocolLib.

I suggest updating to latest java 8. Errors like these can potentially be caused by certain bugs fixed in later java versions

**Comment by yyunusyigit** [comment] 2018-08-30 22:12
We updated Java. We will wait for the problem to recur. It can take a long time, the problem does not happen immediately. Occurs randomly and rarely.

**Comment by yyunusyigit** [comment] 2018-09-05 10:26
Problem not solved with latest java version.

Error: https://hasteb.in/zexelosi.css

**Comment by irworks** [comment] 2018-09-10 13:30
We are having the same issue, a couple instances a week are failing with mentioned error. The most problematic part of this is that most of the time the issue freezes the main thread. I attached a log file containing the full thread dump.
[latest.log](https://github.com/konsolas/AAC-Issues/files/2366777/latest.log)

**Comment by yyunusyigit** [comment] 2018-09-13 13:43
@konsolas  and other startup error: https://hasteb.in/exucuyug.md

**Comment by craftrise** [comment] 2018-09-26 18:35
@konsolas and new problem, the server does not stop and continues forever: (0 Online)

Profiler 1: http://prntscr.com/kz2wm2
Profiler 2: http://prntscr.com/kz2wye
Htop: http://prntscr.com/kz2x4t

Profiler output: https://hasteb.in/pohazazu.nginx

**Comment by yyunusyigit** [comment] 2018-09-26 18:36
@konsolas and new problem, the server does not stop and continues forever: (0 Online)

Profiler 1: http://prntscr.com/kz2wm2
Profiler 2: http://prntscr.com/kz2wye
Htop: http://prntscr.com/kz2x4t

Profiler output: https://hasteb.in/pohazazu.nginx

**Comment by irworks** [comment] 2018-09-26 19:05
@yyunusyigit This seems to match mostly our issue, for reference also our profiler information. Interestingly the exception occurred in "Thread-31", this Thread seems vanished (finished before attaching the profiler?) but does not appear blocking. So that the exception in "Thread-31" causes a somehow semi-blocking hold on the main server thread?
![image](https://user-images.githubusercontent.com/5793142/46102716-4aac5880-c1cf-11e8-92b3-cf5e04231826.png)

**Comment by MedicOP** [comment] 2018-09-29 21:52
https://github.com/konsolas/AAC-Issues/issues/537

**Comment by irworks** [comment] 2018-09-29 22:01
@MedicOP Yes, this happens totally random. Even without the profiler.

**Comment by Janmm14** [comment] 2018-09-29 22:06
profiler stuff with weakhashmap looks really suspicious

the stuff before clearly looks like it could be issue 537 as MedicOP pointed out.

**Comment by irworks** [comment] 2018-09-30 00:34
@Janmm14 Just to clarify: The stuff before (at least at our‘s) happens without any profiler attachment in production since Version 3.5. Please check with the latest.log provided in my comment 13 days ago.

**Comment by yyunusyigit** [comment] 2018-10-05 09:50
@konsolas, other crash error: https://pastebin.com/XYw9HWVi

**Comment by yyunusyigit** [comment] 2018-11-01 16:40
@konsolas, with 3.6.2 new startup error: 
![image](https://user-images.githubusercontent.com/39746552/47865713-f750aa00-de0d-11e8-8ef3-616a72dc3a31.png)

**Comment by yyunusyigit** [comment] 2018-11-01 20:41
@konsolas, and teleport event null pointer:
![image](https://user-images.githubusercontent.com/39746552/47878545-9e920900-de2f-11e8-83cb-9a188c91f3f4.png)

**Comment by yyunusyigit** [comment] 2018-11-04 21:35
Note: We are using version 3.3.12 because the problem is not resolved and the developer is not interested.

**Comment by Janmm14** [comment] 2018-11-21 01:12
Please try using oracle jdk indtead of openjdk.

Please report other errors like the npe in other issues.

**Comment by yyunusyigit** [comment] 2018-12-30 11:50
We have been using the older version for 1.5 months and there is no problem. (Version: 3.3.15)

**Comment by Janmm14** [comment] 2018-12-30 12:13
Did oy uried using oracle jdk 8 instead of openjdk?

**Comment by Janmm14** [comment] 2018-12-30 12:44
@yyunusyigit The startup errors you have are likely coming frm obfuscation / leak protection. And I think you should give it a try at least. I never had such errors. And I use oracle jdk.

**Comment by yyunusyigit** [comment] 2019-02-02 16:16
Welcome February!

**Closed** 2019-07-20 17:43 UTC
Labels: 1. error, 3. recheck newest version
