### ISSUE TITLE
Error message (Official spigot?!)

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#293] opened 2016-12-27 19:18 UTC
https://hastebin.com/kebukawiku.sql

im getting this error, i dont know what is causing it but its saying im not using official spigot while im for sure running official spigot 1.11.2

**Comment by Janmm14** [comment] 2016-12-28 03:46
CraftWitherSkeletons do not a getHandle method for whatever reason according to konsolas.

**Comment by Janmm14** [comment] 2016-12-28 12:18
Actually this is a duplicate of #275.

**Closed** 2016-12-28 12:18 UTC
Labels: duplicate, error
