### ISSUE TITLE
Teleporting to the ground BUG

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#798] opened 2017-07-03 20:38 UTC
AAC breaks teleportation , players constantly fall under the ground!
This bug appeared 3 or 4 updates back and has not yet been fixed!
Or tell me what kind of check it affects so that we can turn it off.
Fix it please!

**Comment by konsolas** [comment] 2017-07-03 21:41
Duplicate of #753

**Closed by konsolas** 2017-07-03 21:41 UTC
Labels: duplicate
