### ISSUE TITLE
[bug] head forced to snap up when mining directly down.

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#1082] opened 2017-11-17 13:57 UTC
You should not be having your head snapped above you when your trying to break a block under you. You are forcibly made to look in a different direction, normally straight up. I was not making my player look up after breaking a block below me. 

Effects currently active: Haste 2

Tools And Effects:

Diamond Pickaxe with:

Efficiency 5

Silk Touch

Unbreaking 3

Mending

Two videos from my players.
https://www.youtube.com/watch?v=ta_z-dy_8ds

In the 2nd videos case, sometimes the block refuses to break under you, and you have to try multiple times to break it or get off the block entirely. 
https://www.youtube.com/watch?v=MJq-IwcYY5c

**Comment by CeIebrimbor** [comment] 2017-11-17 15:34
Fly settings?

**Comment by Janmm14** [comment] 2017-11-18 13:57
usually this is no bug, but wanted so people do not gather phase/fly violations that quickly.
in those cases, a teleport is initiated with a changed pitch.
so you do not constantly mine downwards or in restriced areas do not always jump and place blocks below you.

so the bug is not that the pitch is set to 0, but the bug is that mining downwards triggers phase or fly.

**Comment by MadMageKefka** [comment] 2017-11-19 23:25
Same as https://github.com/konsolas/AAC-Issues/issues/1041

**Comment by Janmm14** [comment] 2017-11-20 00:23
Closing as duplicate of #1041 then

**Closed by Janmm14** 2017-11-20 00:23 UTC
