### ISSUE TITLE
Jump potion at block edge = Fly

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#430] opened 2017-02-05 18:43 UTC
https://youtu.be/hbxxYU2vFXo

Log: https://hastebin.com/epegusalol.hs

### Core information
**Server version**: Paper 1.11.2

**AAC version**: 3.0.3

**ProtocolLib version**: 4.2.1

**Plugin list**: Only thing changing movement is Jump II boots that apply the potion effect.

### Special environment information
NONE

**Comment by CeIebrimbor** [comment] 2017-02-05 19:26
Can't replicate on test server, so seems 1.11 exclusive.

**Comment by Pluginsel** [comment] 2017-02-05 19:52
on version 1.8 working, please fix!

**Comment by Acenox2** [comment] 2017-02-06 00:22
Hello,

I have a server Mini-games, I have the same problem with my players, thanks to a kit, they have jump-boost and there is a lot of false positive because of this. Can you fix it please! Thank you :)

**Comment by Photon-GitHub** [comment] 2017-04-02 17:27
I can no longer reproduce that on 1.8, therefore I will close this as fixed.

**Closed by Photon-GitHub** 2017-04-02 17:27 UTC
Labels: bug, move
