### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Tobi-Jakka** [konsolas/AAC-Issues#2138] opened 2021-01-20 23:16 UTC
**Console Log**:
https://pastebin.com/SWJYtjA1

**AAC Log**: No log

### Core information
**Server version**:  paperspigot 1.16.4

**AAC version**:  5.0.8
**AACAdditionPro version**: 6.4.0
**AACPlus**: 3.0.0

**ProtocolLib version**: 4.5.1

**Plugin list**: 
AAC5, AACAdditionPro, AACPlus, AdvancedAchievements, AsyncWorldEdit, AuctionHouse, ChatControlRed, ChestShop, Citizens, CommandAlias, ConditionalCommands, CoreProtect, CrateReloaded, EnchantmentsPlusMinus, Essentials, EssentialsProtect, EssentialsSpawn, ezAuctions, ForumConnect, HolographicdDisplays, IllegalStack, LiteBans, LuckPerms, mcMMO, MessageAnnouncer, MineableSpawners, MobArena, Multiverse-Core, PL-Hide-Pro, PlaceholderAPI, PlayerTime, PlayerVaults, Plugman, ProtocolLib, QuickWarps, ServerListPlus, ShopGUIPlus, ShopGUIPlusMineableSpawnersBridge, Skylyfe, TAB, Tokenmanager, UltraMinions, Vault, ViaBackwards, ViaVersion, VoidGenerator, VoteParty, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags
### Special environment information
**ViaVersion version**: 3.2.1

**ProtocolSupport version**: Not using

**ViaBackwards version**: 3.2.1

**BungeeCord plugins**:  None

### Configuration
Sorry eh didnt know how to use that website as there was no save button + I couldnt find the default AAC config.. But well this is my config file:
https://pastebin.com/u4Qjwy6t

**Comment by Janmm14** [comment] 2021-01-21 08:42
Duplicate of #2135, see here how to fix: https://github.com/konsolas/AAC-Issues/issues/2135#issuecomment-762794935

**Closed** 2021-01-21 08:42 UTC
Labels: 1. error, 4. invalid
