### ISSUE TITLE
Could not pass event PlayerInteractEvent to AAC v3.3.0 org.bukkit.event.EventException

### ISSUE THREAD

**Issue by smartmadio** [konsolas/AAC-Issues#890] opened 2017-08-21 14:19 UTC
Issue description

`[22:11:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AAC v3.3.0
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-916.2]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:496) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:912) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-916.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException`

Core information

Server version: 1.10.2

AAC version: 3.3.0

ProtocolLib version: 4.2.0

Plugin list: insert

Special environment information

ViaVersion version: 1.2.0

ProtocolSupport version: N/A

ViaBackwards version: 2.2.0

BungeeCord plugins: N/A

Configuration

Default configuration

**Comment by konsolas** [comment] 2017-08-21 16:16
duplicate of #881

**Closed by konsolas** 2017-08-21 16:16 UTC
