### ISSUE TITLE
1.12 clients on 1.8 server are stuck in/fail through SOIL

### ISSUE THREAD

**Issue by MineTheCube** [konsolas/AAC-Issues#922] opened 2017-09-04 07:35 UTC
### Issue description

_Updated 5 sept at 9am_

Since `3.3.1`, players in recent versions (especially 1.12) will fall/get stuck through `SOIL` blocks on 1.8.8 servers. Then they are stuck and kicked for fly when they try to move/jump too much. I can add more information if you need to, but this is relatively easy to reproduce.

- Gif with 1.12.1 client:
![https://i.imgur.com/qYUqTxO.gif](https://i.imgur.com/qYUqTxO.gif)

- Logs (corresponding with above gif): [https://pastebin.com/etiA8ad0](https://pastebin.com/etiA8ad0)

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.2-b1

**ProtocolLib version**: 4.2.0 (same issue on ProtocolLib 389)

**Plugin list**: _not relevant_

### Special environment information
**ViaVersion version**: 1.2.1

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: _not relevant_

### Configuration

Using default config.

**Comment by CeIebrimbor** [comment] 2017-09-04 15:44
@MineTheCube 
Can you give ProtocolLib 4.2.0 a try? If the same occurs after that downgrade, I can/will remove the "Insufficient Info". 4.3.0 has been known to cause issues with 1.8.8 servers.

**Comment by Janmm14** [comment] 2017-09-04 18:56
`Fall` or `get stuck`? Or is that random?

**Comment by JuliCarles** [comment] 2017-09-04 21:33
Having this issue as well. Players using 1.11.2 on a 1.8.8 server get stuck in soil blocks.

**Comment by MineTheCube** [comment] 2017-09-05 06:44
You could `fall` through block in AAC `3.3.1`, in `3.3.2` it seems you only get `stuck`.

I'll try with ProtocolLib `4.2.0`. (is 4.2.1 ok?)

**Comment by MineTheCube** [comment] 2017-09-05 07:17
Updated with AAC `3.3.2-b1`, ProtocolLib `4.2.0`, and using default config.

**Comment by JuliCarles** [comment] 2017-09-10 19:58
> You could fall through block in AAC 3.3.1

It seems you can also fall in 3.3.2-b1.
https://gyazo.com/7bb1d5b7e10d2999e1720cd5e91fac88

**Comment by CeIebrimbor** [comment] 2017-09-18 14:31
I believe this is a vanilla bug. The Minecraft 1.12.2 update addressed multiple issues tied to clients getting stuck in soil or "stuck in fly mode".

Closing unless it is proven that 1.12.2 does not patch this bug.

**Comment by MineTheCube** [comment] 2017-09-18 14:37
@CeIebrimbor this wasn't the case in `3.3.0`, at least players weren't kick for that. Also since servers may not be updated to 1.12.2 before a while, this has to be fixed in AAC.

**Comment by JuliCarles** [comment] 2017-09-18 14:51
Tried on latest version of 1.12.1
This is still happening regarding player reports.

**Comment by CeIebrimbor** [comment] 2017-09-18 14:53
The fact that is exclusively tied to 1.12.1 clients (regardless of server) and that the vanilla bug patches in 1.12.2 are a direct replication of the bug reported here "players stuck in fly mode", leads me to believe it's not AAC's business to try and fix, since the fix is allowing flight.

I suppose I'll let the AAC dev decide if it's worth attention in the next week before 1.12.2 takes over.

**Comment by CeIebrimbor** [comment] 2017-09-18 15:19
**Update:**
After testing by @FrankHeijden on 1.8.8 with the **new** ViaVersion which supports up to 1.12.2, it is reportedly fixed for all 1.12 clients. Looks like ViaVersion adopted the patch for all 1.12.1.

@MineTheCube Can you report if this is fixed after getting the latest ViaVersion?

**Comment by MineTheCube** [comment] 2017-09-18 15:47
Sadly, this is **not fixed**.

Tested right now with:
- Server: ViaVersion `1.3.0`, AAC `3.3.2-b2`, Spigot `1.8.8`, ProtocolLib `4.2.0`
- Client: `1.12.1` _(I am testing newer and older clients...)_

**Comment by CeIebrimbor** [comment] 2017-10-04 18:15
@MineTheCube 
Have you updated to the (seemingly) now compatible dev builds of ProtocolLib? Recent builds (388+) fixed a compatibility with AAC.

Please update to [latest dev build](http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/) and get back. 

If anyone else can confirm this fixed running a 1.8.8 server with latest ViaVersion + the newer ProtocolLib, please advise.

**Comment by MineTheCube** [comment] 2017-10-04 18:42
I just downloaded ProtocolLib `#389`, and using same environment as before (ViaVersion `1.3.0`, AAC `3.3.2`), and I'm still stuck and able to pass through blocks. :/

**Comment by Janmm14** [comment] 2017-10-12 22:32
Confirmed issue.

**Comment by CeIebrimbor** [comment] 2017-10-12 22:34
> Confirmed issue, at least for getting stuck.

Probably no more getting sucked through blocks though (with 3.3.4).

**Comment by MineTheCube** [comment] 2017-10-13 12:03
Issue is still here in AAC `3.3.4`
GIF → [https://imgur.com/Ky88vIS](https://imgur.com/Ky88vIS)

**Comment by Janmm14** [comment] 2017-10-13 12:24
@MineTheCube As this is neither marked fixed nor marked with milestone 3.3.4, it is obviously not fixed, just the teleport inside blocks should be fixed.

**Comment by MineTheCube** [comment] 2017-10-13 16:48
@Janmm14 I don't know what you exactly mean by `teleport inside blocks`, but take a look at the gif I posted, at the end I am teleported under the soil platform.

**Comment by Janmm14** [comment] 2017-10-13 17:42
oops

**Comment by Hyronymos** [comment] 2017-10-18 23:30
Please rename it! 1.8.8 Players getting kicked for the same FP!

**Comment by MineTheCube** [comment] 2018-01-27 20:05
Latest release didn't fix the issue completely. Players don't fall through soil anymore, but they are still kicked for Speed.

Do I need to open another issue?

**Closed** 2018-02-28 18:33 UTC
Labels: 1. bug, 2. move, 3. multiversion, 4. fixed

**Comment by Janmm14** [comment] 2018-02-28 18:34
See #1176
