### ISSUE TITLE
Spam: You cannot register objects without a watcher object!

### ISSUE THREAD

**Issue by wasder** [konsolas/AAC-Issues#1244] opened 2018-03-01 11:42 UTC
Updated to the latest AAC ( 3.3.11)and got this spam now:
https://hastebin.com/exucixemif.sql
ProtocolLib v4.4.0-SNAPSHOT-b390

**Comment by Janmm14** [comment] 2018-03-01 13:20
Duplicate of #1240

**Closed by Janmm14** 2018-03-01 13:20 UTC
