### ISSUE TITLE
Ice fp

### ISSUE THREAD

**Issue by Justinis77** [konsolas/AAC-Issues#1033] opened 2017-10-16 12:03 UTC
### Issue description
I have fp on Ice

### Core information
**Server version**: 1.8.8 Spigot
**AAC version**: 3.3.4
**ProtocolLib version**: 4.2.0
**Plugin list**: AAC, AACadditionpro, ProtocoLib, ConditionalCommands
### Special environment information
**ViaVersion version**:N/A

(Localhost Testserver)
Video: https://youtu.be/LiuRQZo3Okg

AAC Logs: https://pastebin.com/y8YEz3Re

**Comment by Rerd** [comment] 2017-10-16 12:05
You’re meant to replace “insert” with the info.

**Comment by Slimerblue22** [comment] 2017-10-16 13:18
Dupe of https://github.com/konsolas/AAC-Issues/issues/933 #933

**Closed** 2017-10-16 18:28 UTC
Labels: 4. duplicate
