### ISSUE TITLE
Error when join the server trough bungee

### ISSUE THREAD

**Issue by maxlehot1234** [konsolas/AAC-Issues#888] opened 2017-08-20 00:59 UTC
Every time a player join the server, I get this error in the console...
https://pastebin.com/Ee850bre

### Core information
**Server version**: Paperspigot 1.12.1 build 1191

**AAC version**: 3.3.0-b1

**ProtocolLib version**: 4.3.0 build 385
**Plugins**:
![image](https://user-images.githubusercontent.com/5159244/29491183-36b62608-8521-11e7-860b-03a0626bae57.png)
![image](https://user-images.githubusercontent.com/5159244/29491182-2e445f80-8521-11e7-971c-3ac77cb349d0.png)

### Special environment information
**ViaVersion version**: insert (or N/A)

**ProtocolSupport version**: Build 136

**ViaBackwards version**: insert (or N/A)

**BungeeCord plugins**: 
![image](https://user-images.githubusercontent.com/5159244/29491179-1b5d5fb6-8521-11e7-86d5-69583d7ab36c.png)

**Comment by Janmm14** [comment] 2017-08-20 01:27
ProtocolLib b385 is not v4.3.0, but v4.4.0-SNAPSHOT which is not supported.

Duplicate of #855

**Closed by Janmm14** 2017-08-20 01:27 UTC
