### ISSUE TITLE
Placing blocks under each other

### ISSUE THREAD

**Issue by xGlenor** [konsolas/AAC-Issues#2226] opened 2021-03-20 01:10 UTC
Issue description
Is there a chance to block stacking blocks under yourself when the player is unable to build? The player is in a region where he cannot build.
A copy of the debug logs is made at a later time, but from the same action as in the video.

Debug:
https://controlc.com/e08cf4a4

Videos:
https://www.youtube.com/watch?v=hfw8iDDlU_o

Core information
Server version: 1.16.5
AAC version: 5.0.14-b1
ProtocolLib version: 4.6.0

Special environment information
N/A

Configuration
Tested with default values

**Comment by konsolas** [comment] 2021-03-20 15:25
Duplicate of #2165

**Closed by konsolas** 2021-03-20 15:25 UTC
