### ISSUE TITLE
v3 Water Edge Speed/Fly is back

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#344] opened 2017-01-04 12:08 UTC
### Issue Description
 
It's back. #170 https://www.youtube.com/watch?v=3gWbqaPLbpM&feature=youtu.be

### Core information
**Server version**: Tested on the 1.8.8 and the 1.10.2 Test server

**AAC version**:  3.0.1, 3.00(The 1.10.2 test server)

**ProtocolLib version**: 4.20

                                *video may still be processing*

**Comment by CeIebrimbor** [comment] 2017-01-04 15:25
@Rqcco 
This possibly a dupe of #323? The video is still processing 3 hours later but it sounds similar. 323 is already slated to be a patch in 3.0.2.

**Comment by Rqcco** [comment] 2017-01-04 20:24
@CeIebrimbor I'll close it as a dupe

**Closed** 2017-01-04 20:24 UTC
Labels: bug, duplicate
