### ISSUE TITLE
Freecam bug

### ISSUE THREAD

**Issue by TheIronMinerLv** [konsolas/AAC-Issues#976] opened 2017-09-25 05:01 UTC
Hi, I'll be short with this one - it is possible to place spawneggs and light up creepers through walls using freecam. I trued multiple server & client versions, all had the same problem.

I have newest AAC and main server version PaperSpigot 1.8.8. (Also correct Protocollib and ConditionalCommands). I would appreciate if you could fix this, because in faction servers it is possible to just place creeper eggs though walls and.. that is not good.

**Comment by ItzSomebody** [comment] 2017-09-25 05:13
It is recommended to use the proper Issue template

**Comment by Games4k** [comment] 2017-09-25 05:21
AAC is not blocking freecam. If you need freecam protection download aacadditionpro or this one
https://www.spigotmc.org/resources/%E3%80%90antifreecam%E3%80%91-%E3%80%901-7-1-10-x%E3%80%91.45836/

**Comment by ItzSomebody** [comment] 2017-09-25 05:28
@Games4k AAC is **supposed** to block freecam via Interact check. Also, Photon told him to come over here to report the issue.

**Comment by TheIronMinerLv** [comment] 2017-09-25 05:36
@Games4k it blocks placement between walls (like inside), not other side of wall...

**Comment by Janmm14** [comment] 2017-09-25 11:13
As you can see in the config, interacting and placing is only cancelled by default after a certain violation level (vl) is reached: https://gist.github.com/konsolas/400c9678e0264fab8d04d84780ec4c63#file-config-yml-L457

**Comment by Janmm14** [comment] 2017-09-25 12:20
I just remembered this issue was already psoted in the past. Closing as duplicate of #921 and #465.
In case setting
```yaml
    cancel_vl_interact: 0
    cancel_vl_place: 0
```
does not help resolving the issue, feel free to ad a comment here and this issue will get reopened.

**Comment by TheIronMinerLv** [comment] 2017-09-25 13:30
Hi, I just tried to set that, both of them to "0", but that didn't helped at all. I restarted my server multiple times, plugin didn't even recognised that placement as hacks.

That was with AAC 3.3.3

**Comment by Janmm14** [comment] 2017-09-25 13:45
I asked for more clarification with verbose output enabled.

**Comment by TheIronMinerLv** [comment] 2017-09-25 14:16
There wasn't any verbose outputs, as I stated previously.

**Comment by Rerd** [comment] 2017-09-25 16:18
Video Here

I changed them both to 0, and it still didn't block the interactions.

**Comment by TheIronMinerLv** [comment] 2017-09-26 14:13
Just an update: I was able to fix this with Skript, not an ideal solution, but will work for now (until AAC would fix this), if someone want the code: https://pastebin.com/YDQtZWeu

**Comment by Janmm14** [comment] 2017-09-26 15:07
Note: You will see some issues with reaching through non-full-blocks (stairs, halfslab, signs) with that.

**Comment by TheIronMinerLv** [comment] 2017-09-26 15:08
Well but it is a solution anyway, for now at least.

**Comment by konsolas** [comment] 2017-10-09 17:26
You would probably see the detection in the debug log, but not in verbose due to the violation having a value of 0 (this is due to a previous request).

The violation will be nonzero in future versions if the player is holding a spawn egg.

**Comment by TheIronMinerLv** [comment] 2017-10-09 17:28
So this will be fixable?

**Comment by konsolas** [comment] 2017-10-09 17:35
It will be fixed in the next update.

**Comment by Janmm14** [comment] 2017-10-09 18:39
@konsolas And what about pressing buttons, switching levers, etc?

**Comment by konsolas** [comment] 2017-10-09 18:48
the bug of min_vl being zero was also corrected, setting it to zero will cancel those interactions as well.

**Comment by Matthew777k** [comment] 2017-11-09 19:01
Not fixed - still working on recent update.

**Comment by Matthew777k** [comment] 2017-11-10 01:19
This still works as of the recent update.

https://youtu.be/rhyQBAsxDxI

**Closed** 2018-07-22 13:31 UTC
Labels: 1. bug, 2. world
