### ISSUE TITLE
Speed FP while placing blocks.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#314] opened 2016-12-29 19:29 UTC
When you place blocks under yourself very fast, it false bans for speed.

Video: https://www.youtube.com/watch?v=12rXzOcn7gA&feature=youtu.be

Config: https://hastebin.com/efusamituf.bash

Server Version: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)

AAC version: Newest 3.01 (Image: https://gyazo.com/1d2b0118a03e050a77c9d24f55492007)

ProtocolLib version: Newest 4.20

Plugin list: 22 Plugins (Image: https://gyazo.com/2878bb99654c8feb8f18f00713aa534d)

Special environment information

ViaVersion version: None

ProtocolSupport version: 4.24

ViaBackwards version: None

BungeeCord plugins: 6 Plugins (Image: https://gyazo.com/c320565a7e3167b4aa518dd9535cc3d2)

**Comment by geNAZt** [comment] 2017-01-02 23:59
Duplicated by https://github.com/konsolas/AAC-Issues/issues/307

**Comment by konsolas** [comment] 2017-02-19 16:51
will close as duplicate of #390

**Closed by konsolas** 2017-02-19 16:51 UTC
Labels: bug, duplicate, move
