### ISSUE TITLE
Stuck after teleportation on 1.8 with ProtocolSupport

### ISSUE THREAD

**Issue by oloflarsson** [konsolas/AAC-Issues#833] opened 2017-07-20 09:15 UTC
### Issue description
I am using ProtocolSupport build #93 together with HexaCoord. In this setup 1.8 clients work all OK. However when I add AAC 3.2.2 into the mix, teleportation between worlds on the same server stops working. This only happens for 1.8.9 clients and below. It still works fine on 1.9+.

The player will "get stuck" after teleporting. The player thinks they are moving around since it looks like so on their client but they will just be standing at spawn. There is sprint particles at the feet, head rotation and arm animations is working. But they don't move from the location. Relogging solves the issue.

The bug is 100% replicatable by:

1. Log in with 1.8 client.
2. Teleport to another world map using a command.
3. You are now glitched/stuck.

There is also a probabilistic chance to get stuck when teleporting on the same map. Using my plugin CreativeGates (https://www.spigotmc.org/resources/creativegates.1905) I made two gates just a few blocks from each other. It was possible to get stuck by teleporting multiple times. Say the sixth or seventh time the same issue would happen, even though the teleportation was not between worlds.

Furthermore this is the debug information for a CreativeGates session during which the player Madus teleported between gates till he got stuck. There is just NoFall mentions. No violations or anything: https://pastebin.com/ESDdvc8i So even though AAC is causing the issue together with ProtocolSupport, it's not possible to pinpoin an exact check such as Fly or something.

Further info: Giving the player the permission AAC.bypass does not help. They still "get stuck" in this way. So it seems it's not a false positive. It's some other kind of bug.

Interestingly we ran a debug session with Madus doing the teleport between worlds while having the permission AAC.bypass. This showed up in the debug log:

```
at 03:50:13.130: --- BEGIN DEBUG DATA --- [ping:216 tps:19.94]
at 03:50:29.908: Bukkit setback of Madus: 0.000,0.000,0.000 -> [2954.472,68.000,3015.519] [ping:223 tps:18.859]
at 03:50:30.300: Madus failed Move: (movement validation) sent unsafe movement 2954.472,68.000,3015.519 -> 8.5,65.0,8.5 [ping:0 tps:20.0] VL:10 [ping:223 tps:20.0]
at 03:51:43.848: --- END DEBUG DATA --- [ping:223 tps:19.891]
```

### Core information
**Server version**: This server is running Paper version git-Paper-1150 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**AAC version**: 3.2.2

**ProtocolLib version**: 4.3.0

**Plugin list**: Plugins (67): CleanroomGenerator, PorteCoulissante, ParticlePack, MorePlayerModels2, MCAuthenticator, ServerCinematics, PlayerHeads, dynmap, WorldEdit, Essentials, Chairs, WorldBorder, Votifier, ProtocolLib, LibsDisguises, mcMMO, Vault, ProtocolSupport, MassiveCore, WESS, MassiveTagApi, MassiveBiomes, MassiveLock, MassiveCombat, CreativeGates, MassiveGates, MassiveInhouse, MassiveSigns, WorldGuard, MassivePerms, AAC, Factions, MassiveFx, MassiveQuest, MassiveIntStat, MassiveLight, MassiveAnnounce, MassiveBooks, MassiveBasic, MassiveTickets, MassiveChat, HawkEye, FactionsTax, MassiveHat, AreaShop, MassiveVote, MassiveMoney, AACAdditionPro, MassiveMobs, MassiveMagic, MassiveShop, MassiveLag, MassiveSnow, Citizens, FactionsDynmap, TradeMe, MassiveTraits, MassiveDisguises, WGRegionEvents, ConditionalCommands, MassiveSharding, Vampire, MassiveVanilla, HolographicDisplays, MassiveRestore, MassiveChar, Sentinel

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: https://build.true-games.org/job/ProtocolSupport/93/

**ViaBackwards version**: N/A

**BungeeCord plugins**: Using HexaCord https://github.com/HexagonMC/BungeeCord/releases

### Configuration
```
move:
   enabled: true
   min_balance: -90
   cancel_threshold: 5
   reset_level: -1
   balance_cap: 10
   decay: 25
```

**Comment by oloflarsson** [comment] 2017-07-20 13:10
@konsolas - I'm putting a 50USD bounty on this one. If you pretty please fix this issue so I don't have to revert back to NoCheatPlus I'll donate 50USD to you.

**Comment by oloflarsson** [comment] 2017-07-20 13:12
Since time is really of the essence said bounty expires 25 July.

**Comment by jordinjm** [comment] 2017-07-22 02:37
I experience this even without protocol support. It seems like some teleport causes creates a desync between the client and the server. A very easy way to reproduce this is to run this command with AAC installed:
`/minecraft:tp @p ~ ~1 ~`

**Comment by jordinjm** [comment] 2017-07-22 02:49
I recorded a quick video you can see this bug in action on a 1.12 paper spigot server running 2 plugins (ProtocolLib and AAC): https://www.youtube.com/watch?v=4ThwK5rwz-g

**Comment by Janmm14** [comment] 2017-07-22 07:24
@jordinjm
Please provide server version, client version and noteable plugins in text too.

**Comment by jordinjm** [comment] 2017-07-22 16:48
**Server Version**: Minecraft (Mojang Synergies AB (Microsoft)) "PC/JAVA Edition" **Full Release 1.12** Using **Paper Clip b1147** for Minecraft **Full Release 1.12**.

**Client Version**: Minecraft (Mojang Synergies AB (Microsoft)) "PC/JAVA Edition" **Full Release 1.12**

**Notable Plugins**: AAC and ProtocolLib.

**AAC** is a notable plugin because this is the issue tracker for **AAC**.
**ProtocolLib** is a notable plugin because it is a dependency for **AAC**.

**Comment by half-cambodian-hacker-man** [comment] 2017-07-22 17:15
+1 - Having this issue on my own server, on 1.11 Spigot with Waterfall.

Please fix this quickly!

**Comment by AppleDash** [comment] 2017-07-22 18:03
I'm having this issue on my server, running behind latest Bungeecord with latest version of PaperSpigot for 1.12, AAC, and ProtocolLib. I'd appreciate if this got looked at!

**Comment by jordinjm** [comment] 2017-07-30 18:53
Is this going to be fixed in the near future?

**Comment by PatoTheBest** [comment] 2017-08-04 03:24
+1
Same issue occurs on our server with Waterfall and 1.11 PaperSpigot server, suing latest version of AAC

**Comment by BestMark** [comment] 2017-08-04 12:34
I have same issue. Please, fix it as soon as possible. 
I'm using Spigot 1.12 (latest build) and ProtocolSupport.

**Comment by CeIebrimbor** [comment] 2017-08-04 14:27
Please keep in mind that konsolas(AAC dev) is on vacation without PC for the next 4-6 days (he has also been gone on said vacation since the day this issue was opened). He has talked with the original reporter and noted that he will look into it and has ideas on how to fix, so we just need to wait for him to return.

Thank you for the feedback and additional info.

**Comment by Janmm14** [comment] 2017-08-12 22:13
Leme just quickly add that ProtocolSupport is no official supported plugin and listed as such in the AAC Overview:
```
AAC may be incompatible with:
[...]
   * Any sort of protocol hack (apart from ViaVersion 1.8-1.11)
[...]
```

**Comment by Janmm14** [comment] 2017-08-20 01:51
@oloflarsson Can you create a new /aacdebug log with AAC 3.3.0-b1 please?

**Comment by jordinjm** [comment] 2017-08-20 03:02
https://pastebin.com/aHZM4dw6
At line 438 (between ticks 3392 and 3393), you can see when I ran `/minecraft:tp Jordin ~0.1 ~ ~`.
Please fix this issue. This is not an issue with protocol support. I have demonstrated this issue on a server running only AAC and ProtocolLib and provided have a 1 command, reproducible way to cause this issue.

**Comment by Janmm14** [comment] 2017-08-20 08:40
Did you got teleported in your client?

**Comment by half-cambodian-hacker-man** [comment] 2017-08-20 08:41
Did you watch his video?

**Comment by Janmm14** [comment] 2017-08-20 09:33
I was referring to @jordinjm's message

**Comment by konsolas** [comment] 2017-08-20 14:31
Going to continue discussion on #879 due to the larger amount of info there.

**Closed by konsolas** 2017-08-20 14:31 UTC
Labels: bug, compatibility, critical, duplicate, move
