### ISSUE TITLE
v3 Jumpboost with Fence gates

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#265] opened 2016-12-17 14:12 UTC
Really self explanatory, if you use jumpboost 2 and try to jump to the top of a fence gate, you get setback.

**Comment by Janmm14** [comment] 2016-12-25 22:58
Seems to onyl setback when jumping while being directly near the fences

**Comment by Janmm14** [comment] 2017-01-22 10:47
Possibly fixed by small movement prediction in 3.0.2

**Comment by Photon-GitHub** [comment] 2017-01-28 11:41
still valid.

**Comment by Photon-GitHub** [comment] 2017-04-02 17:22
I cannot reproduce this anymore, therefore I will close this as fixed.

**Closed by Photon-GitHub** 2017-04-02 17:22 UTC
Labels: bug, move
