### ISSUE TITLE
Name duplication problem

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#1242] opened 2018-03-01 07:43 UTC
There is a name duplicating problem in AAC new version:
https://imgur.com/a/gmZTP
Also, the NPCs that flies arround you to find a killaura hacker, gets duplicated.

**Comment by Rerd** [comment] 2018-03-01 11:34
Neither of these are issues, they’re both features.
These are a part of the remade Killaura check.
Turn off your esps so you cannot see them or don’t cheat.

**Comment by BlackDemonZetaxd** [comment] 2018-03-01 11:37
Is  happening the same without ESP .-.

**Comment by Janmm14** [comment] 2018-03-01 13:12
Duplicate of #1239

**Closed by Janmm14** 2018-03-01 13:12 UTC
