### ISSUE TITLE
Blocking flying elytra

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#866] opened 2017-08-08 14:19 UTC
### Issue description

https://youtu.be/u2bG-EQ4UVk

### Core information
**Server version**: 1.12

**AAC version**: 3.2.2-b1

**ProtocolLib version**: 4.3.0

**Plugin list**:
http://imgur.com/a/Bcpma

### Special environment information
**ViaVersion version**: 1.1.0

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
configuration default (translated notyfications)

**Comment by Photon-GitHub** [comment] 2017-08-10 15:12
The general elytra handling needs a revamp, therefore I mark this issue as critical.

**Comment by ProDash1998** [comment] 2017-08-11 07:57
and have next problem not work me aactoogle(verbose)

**Comment by CeIebrimbor** [comment] 2017-08-11 20:35
Also see #773

**Comment by konsolas** [comment] 2017-08-14 10:50
Closing as a duplicate of the elytra component in issue #773

#773 is now critical.

**Closed by konsolas** 2017-08-14 10:50 UTC
Labels: bug, critical, duplicate, move
