### ISSUE TITLE
null

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#1266] opened 2018-03-04 11:18 UTC
### Issue description
https://paste.md-5.net/xuxosaxigu.java
https://paste.md-5.net/fafedowupo.avrasm

### Core information
**Server version**: CraftBukkit version git-Spigot-4bd94dc-fb414fe (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**AAC version**: 3.3.11-b1

**ProtocolLib version**: ProtocolLib v4.4.0-SNAPSHOT-b390

**Plugin list**: n/a

### Configuration
cel's

**Comment by Janmm14** [comment] 2018-03-04 13:34
First one likely duplicate of #1254 

Second one not enough information.
A bug report about movement checks requires more information about the situation.

Use /aacdebug to toggle debug logging to a file in `plugins/AAC`.

Additionally it would be great to have a short description of the actions done - were blocks build, broken near you?

Verbose information alone is not enough to  fix false positives.

**Comment by FrankHeijden** [comment] 2018-03-04 13:36
Nono, this is all one issue, i used the aaclog for displaying what happened while the error occured as i couldn’t replicate

**Comment by Janmm14** [comment] 2018-03-04 13:39
Can you search your log form the start where the error is bigger please?

**Comment by FrankHeijden** [comment] 2018-03-04 13:40
Its not bigger, i copied this directly from my log file, it is just like this lol.

**Comment by Janmm14** [comment] 2018-03-04 14:32
The error is defintiely shortend by the java runtime which just happens after some time if the error happens often.

**Comment by FrankHeijden** [comment] 2018-03-04 16:06
https://paste.md-5.net/wesaledoma.java

**Comment by Janmm14** [comment] 2018-03-05 01:11
Ok, its the same error as in #1254, thanks for checking again.

**Closed** 2018-03-05 01:12 UTC
