### ISSUE TITLE
1.8.8 server and different client versions movement blocked with official client

### ISSUE THREAD

**Issue by mechoriet** [konsolas/AAC-Issues#1699] opened 2019-08-07 18:21 UTC
### Issue description

after a bit of "testing" just plain running at normal speed and got down to 3 foodbars and then eated apples till full bars and started running again
i keep getting slowed down + cant turn myself arround (getting set back to old position what it seems)

and i see alot "DevMechoriet failed time: sent too many packets: 311.88 [ping:14 tps:20.0] VL:1-51" and higher seen

and a lot of invalid movement verbose messages

https://gist.github.com/mechoriet/8f5d9508a2aa961afbc240ab31fcf67b

### Core information
**Server version**: 1.8.8(perfectspigot)

**AAC version**: 2.0.10

**ProtocolLib version**:  4.4.0

**Plugin list**: 
[20:15:42 INFO]: Plugins (43): LagAssist, LuckPerms, CrazyCrates, ClearLag, PlugMan, spark, NametagEdit, PandaWire, BookDuplicationFix, Multiverse-Core, FastAsyncWorldEdit, Libs4Paper, ViaVersion, CraftingStore, Vault, CannonPatches, ShopGUIPlus, Essentials, FastAsyncVoxelSniper, ProtocolLib, AAC, Citizens, ChestCommands, CentrixCore, AACPlus, VoxelSniper, CrazyAuctions, ConditionalCommands, CommandNPC, EssentialsSpawn, WorldEdit, AACAdditionPro, HolographicDisplays, WorldGuard, Factions, FramePicture, EpicBuckets, ObsidianDestroyer, StackMob, CombatTagPlus, AdvancedEnchantments, CrazyEnvoy, NoFlyZone

### Special environment information
**ViaVersion version**: 2.1.3

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: 

### Configuration
i use the "Celebrimbor optimized config"

**Comment by mechoriet** [comment] 2019-08-07 18:26
also happend with full food arround a tree(look image)
![image](https://user-images.githubusercontent.com/4313219/62647690-6769fe80-b951-11e9-9824-e1be2cd27f18.png)

on another staff at our server

**Comment by Janmm14** [comment] 2019-08-07 18:35
1. aac does not support 1.7 clients
2. do you run any kind of protocol plugin (viaversion/protocolsupport) on bungeecord, if you have bungeecord?
3. can you try this with normal spigot?

**Comment by mechoriet** [comment] 2019-08-07 18:58
1. the was 1.8.8
2. no
3. i can try that if needed

**Comment by konsolas** [comment] 2019-08-07 19:35
Please do

**Comment by mechoriet** [comment] 2019-08-07 20:42
on This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

if works normal this in the only verbose output when you start to slow down from the hunger
![image](https://user-images.githubusercontent.com/4313219/62656488-90e05580-b964-11e9-9874-57e4d28bc811.png)

and can still move arround in slow and after eating

**Comment by mechoriet** [comment] 2019-08-07 20:52
but that was a clean server gonna check it now in a clone of the same server where i had the problem with a plain spigot jar

**Comment by mechoriet** [comment] 2019-08-07 21:10
on a clone with plain spigot
it also doesnt happen
you only get one invalid movement when you hit the 3 bars(i think because you slow down)
but then after eating i can still move so hmmm

**Comment by Janmm14** [comment] 2019-08-07 21:15
That one move violation (where you tested with clean spigot) is probably happening because the server has set the clients hunger already to 3, but  the client has not yet recieved that change and thinks it still has more food left. Generally a single violation with vl 4 can normally be ignored.

**Comment by mechoriet** [comment] 2019-08-07 21:29
with normal tacospigot its also working fine
so hmmm

**Comment by Janmm14** [comment] 2019-08-07 22:05
maybe there is some bug with hunger level in api in that buyable fork or so. i suggest maybe contacting the developer of perfectspigot and say that you might have found a bug.

**Comment by konsolas** [comment] 2019-08-08 17:22
I agree - this appears to be a bug with your fork of spigot, given that everything works as expected on normal/paper/taco spigot.

For now, I'm going close this because it's not a bug with AAC.

**Closed by konsolas** 2019-08-08 17:22 UTC
Labels: 1. bug, 2. move, 3. specific-setup

**Comment by didjee2** [comment] 2019-08-08 22:08
Update on this issue, @konsolas (not sure if you see this if I don't tag you, as it's closed already).

The food thingy explained above seems to only happen on the PerfectSpigot build, but what you see in the video's I link below seems to happen in:
- PerfectSpigot
- TacoSpigot
- PaperSpigot

(I am yet to test Spigot itself, but I'm about to sleep)

I made two video's about it, one for:
- PerfectSpigot (other map): https://youtu.be/vcGe9Bw-7RI
- PaperSpigot: https://dev.dbsoftwares.eu/aac_papermc.mp4 (youtube got stuck on processing so uploaded it to my site)

I am basically just jumping around this tree (different block heights (slabs)), and every time I started glitching (and aac verbose got spammed):
![image](https://user-images.githubusercontent.com/12124549/62740150-3fed6180-ba37-11e9-9dfb-39a02c73bc02.png)

One small note though, this happened faster in TacoSpigot then in PaperSpigot (had to jump around longer in PaperSpigot).

Also, once it started glitching, it didn't really stop till I stood still multiple seconds or till I rejoined.
Plugin list is also the same as mentioned in initial message.

AAC log: https://paste.dbsoftwares.eu/rocijaqito.css

**Comment by Janmm14** [comment] 2019-08-09 09:36
I'm wondering also about the "timer" problems in the logs. The timer check should be pretty accurate but it is not for you somehow :/

**Comment by didjee2** [comment] 2019-08-09 10:37
> 
> 
> I'm wondering also about the "timer" problems in the logs. The timer check should be pretty accurate but it is not for you somehow :/
> 
> Do you have asnyc enabled for move? If yes, does it help if you turn that off?

It's on false (move.async in aac config)

**Comment by konsolas** [comment] 2019-08-09 16:13
If the tree issue still happens on a vanilla client with AAC 4.0.11 and spigot/paperspigot, please open a separate issue - we're currently trying to make sure each issue contains exactly one problem.

**Comment by didjee2** [comment] 2019-08-09 19:51
> 
> 
> also happend with full food arround a tree(look image)
> ![image](https://user-images.githubusercontent.com/4313219/62647690-6769fe80-b951-11e9-9824-e1be2cd27f18.png)
> 
> on another staff at our server

It happens with a vanilla client and I though just mentioning it here because it's the same problem.

The test was in AAC 4.0.10 though, so I'll test it again with newest version.
