### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1139] opened 2018-01-05 11:57 UTC
### Issue description
Log: https://pastebin.com/WVV737Pn

### Core information
**Server version**: Paper 1.12.2

**AAC version**: Latest (3.3.7-b2)

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Special environment information

**ProtocolSupport version**: buildnumber: 178

**Comment by Janmm14** [comment] 2018-01-06 00:12
Duplicate of #1138

**Closed by Janmm14** 2018-01-06 00:12 UTC
Labels: 1. error, 2. combat, 4. duplicate

**Comment by Toshka17** [comment] 2018-01-06 00:49
These are different errors, no?
