### ISSUE TITLE
NullPointerException in EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by MinecraftiUndCo** [konsolas/AAC-Issues#964] opened 2017-09-18 18:12 UTC
### Issue description

Console error during operation.

* https://pastebin.com/xNy552wP

### Core information
**Server version**: 1.8.9
**AAC version**: 3.3.2-b2 (newest version)
**ProtocolLib version**: V.4.3.0
**Plugin list**: AAC, AACAdditionPro, ProtocolLib and own plugins

### Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by konsolas** [comment] 2017-09-18 18:16
duplicate of #936

**Closed by konsolas** 2017-09-18 18:16 UTC
Labels: duplicate
