### ISSUE TITLE
Antiknockback Bypass (Reducer)

### ISSUE THREAD

**Issue by lukeaction** [konsolas/AAC-Issues#192] opened 2016-11-13 14:58 UTC
Hello,
In this Video you can see a Knockback-Bypass(Reducer) on the 1.8 Testserver:
https://www.youtube.com/watch?v=qV2FcdL09cQ&feature=youtu.be

**Comment by Photon-GitHub** [comment] 2016-11-13 15:02
Duplicate of #100

**Closed by Photon-GitHub** 2016-11-13 15:02 UTC
