### ISSUE TITLE
TP aura bypass

### ISSUE THREAD

**Issue by level147Missingno** [konsolas/AAC-Issues#781] opened 2017-06-24 04:27 UTC
https://youtu.be/WrtBKNY4YKQ

JigSaw client
TP aura setting: http://imgur.com/a/1Dh8k
by the way, make sure target is set to players only or this bug will fail.

**Comment by byCaptain** [comment] 2017-06-24 07:03
that's not the latest aac, try it on gommehd.net

**Comment by w-o-a-h** [comment] 2017-06-24 11:19
its not bypassing at all you are flagging like crazy and on a server without latest aac

**Comment by Janmm14** [comment] 2017-06-24 14:34
Can't reproduce on AAC 3.2.0 with jigsaw 0.25 for 1.8.8, it flags like hell and gets cancelled all over the place, regardless of settings used.

**Comment by Janmm14** [comment] 2017-06-25 16:48
I can't properly test

**Comment by Janmm14** [comment] 2017-07-04 23:04
fixed in 3.2.1-b1

**Closed by Janmm14** 2017-07-04 23:04 UTC
Labels: bypass, combat, critical
