### ISSUE TITLE
Boats abuse move false-positive

### ISSUE THREAD

**Issue by PinkLolicorn** [konsolas/AAC-Issues#1852] opened 2020-01-03 22:03 UTC
### Issue description
Jump onto boat (without actually entering it) and then go to take a bath by moving into water, you can also push boat after that to magnify effects. Generally speaking any situation while you're in boat hitbox without actually using it as vehicle results in VL increases.

![image](https://user-images.githubusercontent.com/44551064/71751784-fdf90800-2e7c-11ea-9400-8ad9a9cdc8ff.png)

[Raw logs](https://gist.github.com/PinkLolicorn/621e0c4fe58afd159b232a3831893ff9)

### Core information
**Server version**: Paper 1.15.1
**AAC version**: 4.3.4
**ProtocolLib version**:  4.5.0-SNAPSHOT-b439
**ProtocolSupport version**: 4.29-dev

### Configuration
I'm using default generated config.

**Comment by konsolas** [comment] 2020-01-08 19:12
duplicate of #1746

**Closed by konsolas** 2020-01-08 19:12 UTC
Labels: 1. bug, 2. elytra/vehicle, 2. move, 4. duplicate
