### ISSUE TITLE
java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by KolakZ** [konsolas/AAC-Issues#2278] opened 2021-06-26 01:49 UTC
### Issue description
I am getting the following error on startup when using `AAC` on my server:
https://gist.github.com/KolakZ/bd2ddc6f59928ca01db0206057cb8736

### Core information
**Server version**: `1.8.8`

**AAC version**: `5.1.0`

**ProtocolLib version**: `v4.6.1-SNAPSHOT-b505`

### Special environment information
**ViaVersion version**: `ViaVersion v4.0.1-SNAPSHOT`

### Configuration
https://www.mc-market.org/resources/18783/

**Comment by Janmm14** [comment] 2021-06-26 04:08
Duplicate of #2274

**Closed by Janmm14** 2021-06-26 04:08 UTC
