### ISSUE TITLE
PlayerInteractEvent - 3.3.0 Errors

### ISSUE THREAD

**Issue by ViscousSummer88** [konsolas/AAC-Issues#887] opened 2017-08-19 23:32 UTC
### Issue description
Failed Interact event errors.

Paste bin: https://gist.github.com/ViscousSummer88/7ec17353093bffc66b6e7539e6b9c1cc

### Core information
**Server version**: git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: v3.3.0

**ProtocolLib version**: v4.3.0

**Plugin list**: AAC, AsyncWorldEdit, Citizens, CoreProtect, CratesPLus, DiscordMC, dtlTraders, Essentials, FastCraftPlus, GAListener, GriefPrevention, HeadDatabase, Holograms, Jobs, LiteBans, mcMMO, MessageAnnouncer, Multiverse-Core & Portals, MyCommands, PermissionsEx, PerWorldInventory, PlotSquared, PluginMetrics, ProtocolLib, RainbowArmour, RandomTP, ReportRTS, TreeAssist, UltraCosmetics, Vault, Votifer, WorldEdit, WorldGuard

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

No changes.

**Comment by konsolas** [comment] 2017-08-20 14:21
duplicate of #881

**Closed by konsolas** 2017-08-20 14:21 UTC
Labels: duplicate
