### ISSUE TITLE
ProtocolLib 4.4.0

### ISSUE THREAD

**Issue by Games4k** [konsolas/AAC-Issues#967] opened 2017-09-19 13:56 UTC
Add support for the latest protocollib build (_Version 4.4.0 - Build [#386](http://ci.dmulloy2.net/job/ProtocolLib/386/)_)
Its three months now from the latest public build  ([4.3.0](http://ci.dmulloy2.net/job/ProtocolLib/373/)) and some other plugins are requesting us to update to the latest dev build, but AAC is still not compatible with it :/

**Comment by Janmm14** [comment] 2017-09-19 19:41
Basically a duplicate of #855.

**Closed by Janmm14** 2017-09-19 19:41 UTC
Labels: bug, compatibility, duplicate
