### ISSUE TITLE
Step bypass

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#112] opened 2016-10-31 00:05 UTC
The step bypass is still not fixed and I can step 1.5 blocks with flags and 1 block with very few flags.
(src: see skype.)

**Comment by Janmm14** [comment] 2016-10-31 01:01
You can go up to 8.3 blocks with wurst flight on mineplex anticheat mode without a dragback -> once a 8 block step should be possible

**Comment by konsolas** [comment] 2016-11-02 23:05
I'm going to close this as a duplicate of #6 which is more detailed about the exact type of step.

**Comment by Janmm14** [comment] 2016-11-02 23:45
@konsolas This is about being able to step higher than normal, #6 is just a 1-block step

**Comment by CeIebrimbor** [comment] 2016-11-03 03:00
Re-Opened until clarified.

**Comment by v0idst4r** [comment] 2016-11-07 02:40
Huh, in my case 1.5 blocks flagged less than 1 block (no idea why).

**Comment by v0idst4r** [comment] 2016-11-07 02:42
http://m.imgur.com/a9xhuDD

**Comment by konsolas** [comment] 2016-12-02 16:57
Closing as fixed.

**Closed by konsolas** 2016-12-02 16:57 UTC
Labels: bypass
