### ISSUE TITLE
For AAC V3 Hacked-Client video. Please fix for V3.0.3

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#389] opened 2017-01-22 13:50 UTC
Video Link: https://www.youtube.com/watch?time_continue=25&v=wrNjH1FiikA
On enable this AAC V3 hack, player no kick from this server.
AAC Version: 3.0.2 (latest)
NOTE: The video is not mine.

**Comment by Rqcco** [comment] 2017-01-22 14:08
Need more information, what protocollib, what minecraft version? These types of videos with hackers showing off there bypasses are generally invalid as well.

**Comment by Pluginsel** [comment] 2017-01-22 15:06
MC Version: 1.8.8

**Comment by Janmm14** [comment] 2017-01-22 15:52
It would be nice if there is at least a meaningful title and even better if there is a short decription of what the issue is actually. (To be able to search issues much easier and for people like me with crappy mobile internet)

**Comment by konsolas** [comment] 2017-01-22 16:14
Closing due to insufficient information.

**Closed by konsolas** 2017-01-22 16:14 UTC
Labels: bypass, insufficient info
