### ISSUE TITLE
[IMPORTANT] Fly (Wurst Mineplex Fly)

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#116] opened 2016-10-31 13:18 UTC
It flags, but it actually allows you to go 8 blocks up into the air, if you press spacebar while not being near blocks or ice.

Idea to fix: Make vl dependant on the distance moved with a min value (and better also a max)

**Comment by konsolas** [comment] 2016-10-31 21:24
@Janmm14 this doesn't seem to be directly reproducible on the test server. It may have been inadvertently fixed. 

If you can still reproduce this, please show screenshots of locations and settings, or a video if possible.

**Comment by konsolas** [comment] 2016-10-31 21:47
It turns out there was a particular spot on the server where this worked. The area and all similar areas have been fixed in code.

**Closed by konsolas** 2016-10-31 21:47 UTC
Labels: bypass, planned

**Comment by Janmm14** [comment] 2016-10-31 22:30
Seems to be a funny one, wanna share, @konsolas

**Comment by konsolas** [comment] 2016-10-31 22:31
Some extremely old code for boat handling. Some boats hadn't despawned from that area.
