### ISSUE TITLE
Speed lagback while fighting

### ISSUE THREAD

**Issue by Minemaniak** [konsolas/AAC-Issues#1190] opened 2018-02-06 23:05 UTC
I don't have much informations, as issue isn't easy to reproduce on demand, so I couldn't get verbose/debug, I tried for quite some time :/

The problem is, after updating 3.3.7 -> 3.3.9 players started to report irritating lagbacks while pvp'ing.
They were getting to the min_vl (100), as we saw in /aacadmin. We tried to test, it happened a few times while throwing a potions or eating food in fight, but it's not the only scenario according to the reports. 

Everything I currently have are 2 videos

https://www.youtube.com/watch?v=EZ5_CQIhlQ4&feature=youtu.be
In about 0:19 you can see a small lagback and blocking in place.

https://www.youtube.com/watch?v=tL8hrjiZb4U&feature=youtu.be
After enemy dies, you can see a bigger lagback/block in place.

Sorry for no verbose/debug, but it's just too hard to get it. But the issue is real, players are complaining A LOT compared to other issues in the past.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.9

**ProtocolLib version**: 4.2.0

**Plugin list**: on request, only our custom 

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: on request, only our custom 

Config: Cel's config

**Comment by Minemaniak** [comment] 2018-02-06 23:07
There was also user reporting it in this issue's comment https://github.com/konsolas/AAC-Issues/issues/1165 (bobl7 comment)

**Comment by bob7l** [comment] 2018-02-07 09:14
So the best way to reproduce this from my experience is to hit a player while they're running away from you. 

[07-02-2018 04:12:21.806] bob7l failed Hitbox: attacked an entity out of their line of sight (reach: 4.777 blocks) [ping:162 tps:20.0] VL:1
[07-02-2018 04:12:21.955] loop failed Speed: moved too quickly: 1.035 blocks/tick (0.602/0.174)+n -n [ping:105 tps:20.0] VL:25
[07-02-2018 04:12:22.005] loop failed Speed: moved too quickly: 0.590 blocks/tick (0.297/0.092)-n -n [ping:105 tps:19.99] VL:39
[07-02-2018 04:12:26.056] loop failed Speed: moved too quickly: 0.527 blocks/tick (0.493/0.361)+n -n [ping:101 tps:20.0] VL:23
[07-02-2018 04:12:27.356] loop failed Speed: moved too quickly: 0.527 blocks/tick (0.493/0.361)+n -n [ping:101 tps:20.0] VL:39
[07-02-2018 04:12:27.556] loop failed Speed: moved too quickly: 0.841 blocks/tick (0.493/0.636)+n -n [ping:101 tps:20.0] VL:64
[07-02-2018 04:12:27.606] loop failed Speed: moved too quickly: 0.384 blocks/tick (0.293/0.000)+n +n [ping:101 tps:19.99] VL:77
[07-02-2018 04:12:27.706] loop failed Speed: moved too quickly: 0.626 blocks/tick (0.344/0.000)+n +n [ping:101 tps:19.99] VL:91
[07-02-2018 04:12:27.955] loop failed Speed: moved too quickly: 0.324 blocks/tick (0.286/0.000)+n +n [ping:101 tps:20.0] VL:104
[07-02-2018 04:12:28.156] loop failed Speed: moved too quickly: 0.324 blocks/tick (0.311/0.000)+n +n [ping:101 tps:20.0] VL:116
[07-02-2018 04:12:28.306] loop failed Speed: moved too quickly: 0.559 blocks/tick (0.343/0.000)+n +n [ping:101 tps:19.97] VL:130
[07-02-2018 04:12:28.508] (Punisher) ->movement.Speed: Dispatching command aacmessage loop It looks like you might be glitching, please tap sneak and block with your sword
[07-02-2018 04:12:28.556] loop failed Speed: moved too quickly: 0.324 blocks/tick (0.285/0.000)+n +n [ping:101 tps:19.96] VL:142
[07-02-2018 04:12:31.756] bob7l failed Hitbox: attacked an entity out of their line of sight (reach: 2.064 blocks) [ping:159 tps:20.0] VL:1
[07-02-2018 04:12:43.057] loop failed Speed: moved too quickly: 0.527 blocks/tick (0.493/0.361)+n -n [ping:100 tps:20.0] VL:23


Every violation in there is a false positive. This is also using the DEFAULT config (My custom config also has the issue).

**Comment by Minemaniak** [comment] 2018-02-07 16:11
I managed to get 2 debug logs from one scenario (speed fp while chasing enemy in fight), but it's not the only fp. The other one is while eating/throwing potions, and there probably is something else, as you can see on the videos I posted earlier.

https://pastebin.com/iWuB9VCv

https://pastebin.com/LEPAxsEa

**Comment by Minemaniak** [comment] 2018-02-07 16:40
One more scenario reported by player: if you are hitting someone, not getting hits (don't know how is it called in English community, "strafe"?, "combo"?), you get blocked in place sometimes.

**Comment by CeIebrimbor** [comment] 2018-02-07 19:30
Many reports of this.

**Comment by Minemaniak** [comment] 2018-02-19 15:01
Not fixed, now even worse, enemy standing still, I'm hitting him, he gets speed&fly flags. Also happens in combat of course.

**Comment by Rerd** [comment] 2018-02-19 15:53
Turn off strict velocity checking for speed. That will fix issues for speed from what I’ve noticed. The issues for fly are a part of #1207, which should be marked as critical.

**Comment by Minemaniak** [comment] 2018-02-19 16:01
It's temporary fix @Rerd, the issue is still real.

**Closed** 2018-02-19 19:45 UTC
Labels: 1. bug, 2. combat, 2. move, 3. critical, 3. not fixed, 4. fixed
