### ISSUE TITLE
Slime blocks + Pistons false positive

### ISSUE THREAD

**Issue by AndyK77** [konsolas/AAC-Issues#1765] opened 2019-09-01 20:39 UTC
### Issue description
A player reported their slime block elevator not working which can be replicated by placing a slime block on top of a piston and pushing it while standing on top, you will get a false positive for a move check.
Video: https://cdn.discordapp.com/attachments/262588738939387904/617820550294798379/slime_blocks.mp4
Logs: https://gist.github.com/AndyK77/471daa5fd7193307ce3d219b4da023e2

### Core information
**Server version**: 1.14.4

**AAC version**: 4.1.8-b3

**ProtocolLib version**: latest

**Comment by konsolas** [comment] 2019-09-01 20:47
Duplicate of #1702

**Closed by konsolas** 2019-09-01 20:47 UTC
Labels: 4. duplicate
