### ISSUE TITLE
Achievement Errors in Console - AAC 3.3.14

### ISSUE THREAD

**Issue by MatheweB** [konsolas/AAC-Issues#1352] opened 2018-04-09 21:07 UTC
### Issue description
There is an achievement/workbench error in the console that is spamming intermittently.

### Core information
**Server version**: 1.12.2

**AAC version**: 3.3.14

**ProtocolLib version**: 4.3.0

**Plugin list**: https://pastebin.com/Ns0qPHP2

Error Log: https://hastebin.com/zerijufiru.vbs

**Comment by Janmm14** [comment] 2018-05-14 16:28
Closing as duplicate of #1357

**Closed by Janmm14** 2018-05-14 16:28 UTC
Labels: 1. error, 4. duplicate
