### ISSUE TITLE
PlayerMoveEvent NPE AAC 3.0.3 a0.a:380

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#420] opened 2017-02-01 11:54 UTC
### Issue description

The console keeps spamming this:
http://pastebin.com/AFeTegJD

### Core information
**Server version**: PaperSpigot 1.11.2

**AAC version**: 3.0.3

**ProtocolLib version**: 4.2.1-SNAPSHOT-b346

### Special environment information
Insert 'none' if you don't use it

**ProtocolSupport version**: 4.25 b661

**Comment by CeIebrimbor** [comment] 2017-02-01 15:15
#297

**Comment by MClausz** [comment] 2017-02-01 16:14
My exception is different from the #297's, it's a NullPointerException

**Comment by MClausz** [comment] 2017-02-03 05:34
Maybe it was caused by this
PaperSpigot 1.11.2, ProtocolLib build 346 (latest)
`[12:05:02] [Server thread/INFO]: [AAC] REFLECTION ERROR WHILST GROUND CHECKING: 
[12:05:02] [Server thread/INFO]: [AAC] Translation: AAC is not compatible with your server version.
[12:05:02] [Server thread/WARN]: [AAC] Task #51 for AAC v3.0.3 generated an exception
java.lang.IllegalStateException: REFLECTION ERROR
	at me.konsolas.aac.dv.a(dv.java:82) ~[?:?]
	at me.konsolas.aac.dv.a(dv.java:10) ~[?:?]
	at me.konsolas.aac.dv.a(dv.java:69) ~[?:?]
	at me.konsolas.aac.dv.a(dv.java:98) ~[?:?]
	at me.konsolas.aac.a_.a(a_.java:17) ~[?:?]
	at me.konsolas.aac.bb.run(bb.java:7) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1046]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.2.jar:git-Paper-1046]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1046]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1046]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1046]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1046]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodException: com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$a5b77f6a.getHandle()
	at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_101]
	at me.konsolas.aac.dv.a(dv.java:7) ~[?:?]
	... 11 more`

**Comment by Janmm14** [comment] 2017-03-21 22:39
@MClausz does this still happen with latest AAC?

**Comment by MClausz** [comment] 2017-03-22 11:31
Yes, AAC v3.0.5 b1
http://pastebin.com/XbwmBZDK

**Comment by Janmm14** [comment] 2017-03-23 11:40
Okay so this turned into a duplicate of #492.

**Closed by Janmm14** 2017-03-23 11:40 UTC
Labels: error, move
